### ISSUE TITLE
SyntaxKit

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#1000]
[SyntaxKit](https://github.com/soffes/SyntaxKit) - TextMate-style syntax highlighting :large_orange_diamond:

**Comment by lfarah** [comment]
@soffes on what category do you think we can add it?

**Comment by soffes** [comment]
How about a misc? :P

**Comment by miguelarauj1o** [comment]
Closing this because **SyntaxKit** is written in Swift 2.
