### ISSUE TITLE
New entry should go to the bottom

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#1013]
We can make a Danger script that checks if the next line is blank, so we know if the new addition is in the bottom

**Comment by vsouza** [comment]
I'm confused about this, a few months ago I was thinking about alphabetical organization. What u think?

**Comment by lfarah** [comment]
@vsouza let's keep this conversation on  #1014

**Comment by dkhamsing** [comment]
Closing for lack of update, feel free to reopen
