### ISSUE TITLE
New organization

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#1014]
I guess it's time for us to find a better way to organize the order of the libs. We have two options:
1. Alphabetically
2. Stars
3.  Chronological

**Comment by dkhamsing** [comment]
3. Chronological (latest at bottom)

**Comment by vsouza** [comment]
Stars it's complicated. I think that alphabetical makes more sense.

**Comment by vsouza** [comment]
@dkhamsing it's difficult to find in a huge list.

**Comment by dkhamsing** [comment]
I would not go with stars

**Comment by dkhamsing** [comment]
@vsouza if a category is too big, we should split it up

**Comment by lfarah** [comment]
My opinion on going with stars is that it's a way to curate, for example, the best networking library out of all we have, or the best JSON parser

**Comment by lfarah** [comment]
@dkhamsing I understand your point and we started doing that when our **UI** section was too big, but how would you split 40 json parsing libraries?

**Comment by dkhamsing** [comment]
Maybe we should not have 40 json libraries

**Comment by lfarah** [comment]
@dkhamsing I've been thinking about that... Our description says 
> "A **curated** list of awesome iOS ecosystem*
Do you have any idea on a general rule we can make for that?

**Comment by dkhamsing** [comment]
We can require minimum number of stars or ask people to endorse in the pull request with 👍s

**Comment by lfarah** [comment]
I was thinking that after @vsouza finishes his scraper, we could create an universal index showing how good a library is, based on length of README, CocoaPods support, Carthage support, Swift, etc.... Based on that we can easily curate the libs with a bad rating. I don't think that a minimum number of stars would work because I can't tell how many amazing libs have so few stars. I agree that it can be one of the factors in this rating

**Comment by dkhamsing** [comment]
Quality index ™ 
I like it!

**Comment by lfarah** [comment]
@dkhamsing Orta from CocoaPods talks about their Quality Index on [this iPhreaks podcast episode](https://devchat.tv/iphreaks/ips-167-cocoadocs-with-orta-therox) at **10:58**

**Comment by lfarah** [comment]
More about it [over here](https://guides.cocoapods.org/making/quality-indexes.html)

**Comment by miguelarauj1o** [comment]
Have you guys reached a decision?

**Comment by dkhamsing** [comment]
I don't think so 

 Personally I think chronological is the least amount of maintenance 

 Maybe we can communicate this better  so people know that libraries or ordered chronologically

**Comment by vsouza** [comment]
IMHO We don't should have a bot or code to organize readme order. I'm divided between Chronological (by inserct on awesome-ios) or alphabetical, if owner wants to be on first position, just rename your lib to `aaa` 😆  

Quality index, it's not a bad idea, but honestly I don't wanna see an bot set data  on README.md, IMHO.

We're working on site, and with a search system that I've been working, we don't will have any problem with results order.

Just my two cents. ❤️

**Comment by dkhamsing** [comment]
Let's close this for now, there's no update on this issue.

The current organization is **chronological**.

Thanks
