### ISSUE TITLE
SwiftyAvatar

### ISSUE THREAD

**Issue by dkalaitzidis** [vsouza/awesome-ios#1019]
A UIImageView class for creating circular or rounded avatar images, IBDesignable to make all changes via storyboard

https://github.com/dkalaitzidis/SwiftyAvatar

**Comment by lfarah** [comment]
Hey @dkalaitzidis, thanks for contributing! I really liked you lib specially because you took the time to implement IBDesignable, which is just **awesome**. Before adding into AwesomeiOS, I'd like for you to take a look at [Issue 7](https://github.com/dkalaitzidis/SwiftyAvatar/issues/7).

Thanks 😄

**Comment by dkalaitzidis** [comment]
@lfarah, i made the readme changes using the template. You can check it when you have the time.

Thanks

**Comment by lfarah** [comment]
@dkalaitzidis everything looks perfect right now. Adding it to our list! 😉
