### ISSUE TITLE
KZFileWatchers

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#1022]
[KZFileWatchers](https://github.com/krzysztofzablocki/KZFileWatchers) - A micro-framework for observing file changes, both local and remote. Helpful in building developer tools. :large_orange_diamond:

**Comment by lfarah** [comment]
@krzysztofzablocki do you know on what category we could add?

**Comment by krzysztofzablocki** [comment]
I'm torn as it could fit under File, Tools or Rapid Development.

**Comment by lfarah** [comment]
@krzysztofzablocki life's hard, I know! I think it's better under File since Tools would be more if KZFileWatchers was only about building dev tools and we are an iOS list
