### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#1023]
[Version](https://github.com/mrackwitz/Version) - Version represents and compares semantic versions in Swift. :large_orange_diamond:

**Comment by lfarah** [comment]
@mrackwitz do you know on what category we could add?

**Comment by victorgama** [comment]
How about `Data Structures`?

**Comment by lfarah** [comment]
@victorgama this issue is so old that the project doesn't even support Swift 3
