### ISSUE TITLE
MarkupKit

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#1024]
[MarkupKit](https://github.com/gk-brown/MarkupKit) - Declarative UI for iOS applications

**Comment by lfarah** [comment]
@gk-brown do you know on what category we could add?

**Comment by gk-brown** [comment]
@lfarah It could probably go in a few different categories, but "Layout" is probably the most appropriate. Thanks!

**Comment by lfarah** [comment]
Thanks for helping out, @gk-brown 😄
