### ISSUE TITLE
SwiftRouter

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#1025]
[SwiftRouter](https://github.com/skyline75489/SwiftRouter) - A URL Router for iOS, written in Swift 2.2 :large_orange_diamond:

**Comment by lfarah** [comment]
@skyline75489 do you know on what category we could add?

**Comment by skyline75489** [comment]
I believe `Utility ` should be the correct one.

**Comment by lfarah** [comment]
Thanks for helping out!
