### ISSUE TITLE
SwiftValidator

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#1026]
[SwiftValidator](https://github.com/jpotts18/SwiftValidator) - A rule-based validation library for Swift :large_orange_diamond:

**Comment by lfarah** [comment]
@jpotts18 do you know on what category we could add?

**Comment by jpotts18** [comment]
UI -> Form

**Comment by lfarah** [comment]
Hey @jpotts18, thanks for contributing! 👍
