### ISSUE TITLE
Runes

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#1027]
[Runes](https://github.com/thoughtbot/Runes) - Infix operators for monadic functions in Swift :large_orange_diamond:

**Comment by lfarah** [comment]
@thoughtbot do you know on what category we could add?

**Comment by miguelarauj1o** [comment]
Can we close this one due to inactivity?

**Comment by dkhamsing** [comment]
Well
Should Runes be added or not

**Comment by lfarah** [comment]
What about [Rx](https://github.com/vsouza/awesome-ios#reactive-programming)?

**Comment by victorgama** [comment]
IMHO _Functional Programming_ suits this lib better. :)
