### ISSUE TITLE
Xtrace

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#1030]
[Xtrace](https://github.com/johnno1962/Xtrace) - Trace Objective-C method calls by class or instance

**Comment by lfarah** [comment]
@johnno1962 do you know where we could add your lib?

**Comment by johnno1962** [comment]
How do you mean? Tools? Other Xcode?

**Comment by lfarah** [comment]
@johnno1962 **/Tools** works. Thanks for contributing!
