### ISSUE TITLE
Popsicle

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#1034]
[Popsicle](https://github.com/DavdRoman/Popsicle) - Delightful, extensible Swift value interpolation framework :large_orange_diamond:

**Comment by lfarah** [comment]
@DavdRoman do you know on what category we could add?

**Comment by DavdRoman** [comment]
@lfarah I'd suggest Animation.

**Comment by lfarah** [comment]
Thanks for helping us out, @DavdRoman! 😄
