### ISSUE TITLE
PredicateEditor

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#1040]
[PredicateEditor](https://github.com/arvindhsukumar/PredicateEditor) - A visual editor for dynamically creating NSPredicates to query data in your iOS app. :large_orange_diamond:

**Comment by lfarah** [comment]
@arvindhsukumar on what category could we add your lib?

**Comment by arvindhsukumar** [comment]
@Ifarah Database and/or Core Data would be the main categories, since it basically involves generating queries (NSPredicates) at run time. 

Thanks for including it in awesome-ios!

**Comment by lfarah** [comment]
Thanks for contributing, @arvindhsukumar
