### ISSUE TITLE
Siren

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#1046]
[Siren](https://github.com/ArtSabintsev/Siren) - Notify users when a new version of your app is available and prompt them to upgrade. :large_orange_diamond:

**Comment by lfarah** [comment]
@ArtSabintsev do you know on what category we could add?

**Comment by ArtSabintsev** [comment]
Same one as Harpy (https://github.com/vsouza/awesome-ios#app-store)

App Store category :)

**Comment by lfarah** [comment]
@ArtSabintsev thanks for helping out, and good job on the cool lib! 👍

**Comment by ArtSabintsev** [comment]
Thank you!
