### ISSUE TITLE
Rename to Alert & Action Sheet category

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#1051]
There are enough Actionsheet + Alert libraries that the renaming makes sense
- [XLActionController](https://github.com/xmartlabs/XLActionController) - Fully customizable and extensible action sheet controller written in Swift. :large_orange_diamond:
- [TOActionSheet](https://github.com/TimOliver/TOActionSheet) - A custom-designed reimplementation of the UIActionSheet control for iOS
- [DOAlertController](https://github.com/okmr-d/DOAlertController) - Simple Alert View written in Swift, which can be used as a UIAlertController. (AlertController/AlertView/ActionSheet) :large_orange_diamond:
- [CustomizableActionSheet](https://github.com/beryu/CustomizableActionSheet) - Action sheet allows including your custom views and buttons. :large_orange_diamond:

**Comment by lfarah** [comment]
@dkhamsing @vsouza @victorgama?

**Comment by victorgama** [comment]
Whoa. Completely lost track of this one. 
The change seems reasonable, will update it in a couple of minutes!

![](http://i.imgur.com/nfchm3w.gif)

**Comment by dkhamsing** [comment]
Thx!
