### ISSUE TITLE
Form / Settings

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#1065]
1. Should we consolidate "settings" projects to Form
- Should we move Form under Table View..

From #1063  

@lfarah

**Comment by lfarah** [comment]
1. ```/Form & Settings``` section?
2. I don't think so. Forms are a smaller group that only happen to use TableViews, but they are more "advanced".

Take the **Hardware** section as an example.
#### Hardware
```
Bluetooth
Camera
Force Touch
iBeacon
Location
```

Force Touch is a hardware
Camera is a hardware
**Form** is not a TableView. It is way more than that:
![eurekaexample1](https://cloud.githubusercontent.com/assets/6511079/17920106/323b616c-6987-11e6-9367-967daa90d2c2.gif)

What do you think?

**Comment by lfarah** [comment]
Same for @vsouza

**Comment by dkhamsing** [comment]
I'm ok with fothis m and settings 
Thx
