### ISSUE TITLE
theapplaunchpad.com

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#1068]
This looks good http://theapplaunchpad.com/

**Comment by lfarah** [comment]
Interesting!

What about [/Deployment & Distributiin](https://github.com/vsouza/awesome-ios#deployment--distribution) ?

**Comment by vsouza** [comment]
@lfarah & @dkhamsing we can close this?

**Comment by dkhamsing** [comment]
yeah whenever it gets added

**Comment by naeemshaikh90** [comment]
What about this? https://github.com/LaunchKit/LaunchKit

**Comment by dkhamsing** [comment]
Similar? Pls open a pull request

**Comment by dkhamsing** [comment]
In the future, please open a separate issue
thanks

**Comment by naeemshaikh90** [comment]
Yes it's similar website.
