### ISSUE TITLE
TTOpenInAppActivity

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#1069]
[TTOpenInAppActivity](https://github.com/honkmaster/TTOpenInAppActivity) - UIActivity to display "Open In ..." and open UIDocumentInteractionController

**Comment by lfarah** [comment]
@honkmaster do you know on what category we could add?

**Comment by lfarah** [comment]
@honkmaster good idea 👍

**Comment by lfarah** [comment]
@honkmaster do you know any other good *UIAcitvity* libraries?

**Comment by dkhamsing** [comment]
Project is 2 years old.. closing
