### ISSUE TITLE
SwiftyConfiguration

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#1106]
[SwiftyConfiguration](https://github.com/ykyouhei/SwiftyConfiguration) - Modern Swift API for Plist. :large_orange_diamond:

**Comment by lfarah** [comment]
@ykyouhei do you know where we could add it?

**Comment by ykyouhei** [comment]
@lfarah Hi! Thanks !
https://github.com/vsouza/awesome-ios#parsing
