### ISSUE TITLE
SwiftCheck

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#1118]
[SwiftCheck](https://github.com/typelift/SwiftCheck) - QuickCheck for Swift :large_orange_diamond:

**Comment by lfarah** [comment]
@typelift do you know on what category we could add?

**Comment by azawawi** [comment]
I would add it under Testing

**Comment by lfarah** [comment]
@azawawi [Which one](https://github.com/vsouza/awesome-ios#testing)?

**Comment by azawawi** [comment]
@lfarah SwiftCheck :)

**Comment by lfarah** [comment]
@azawawi noo, which category inside **/Testing**?

**Comment by azawawi** [comment]
TDD/BDD

**Comment by lfarah** [comment]
@azawawi thanks for helping out! 🎉
