### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#1124]
Update: 

We want to remove projects that are not compatible with Swift 3
If you know of any, please add them to this issue

Thanks!

---

How long will we wait for the libraries to update to Swift 3 before we start taking them out?
I say we should open issues on all of them and wait a certain period.

**Comment by lfarah** [comment]
@dkhamsing @vsouza

**Comment by dkhamsing** [comment]
Sounds good! I can help you with that :)

**Comment by dkhamsing** [comment]
https://github.com/dkhamsing/new_issue

**Comment by dkhamsing** [comment]
@lfarah can u get me a list of swift projects?

**Comment by lfarah** [comment]
@dkhamsing I wonder how you can create soo many bots...
I will use new_issue a lot!!

Let me get back from work and I'll work on it....

**Comment by dkhamsing** [comment]
fyi will be offline until end of the month, sorry if you dont hear from me 😅

**Comment by vsouza** [comment]
Guys, we have a definition for this?

**Comment by dkhamsing** [comment]
Can you get a list of Swift projects ?

**Comment by vsouza** [comment]
@dkhamsing We're working on that. A few months ago I decided to move to another city and my life turns a little mess. But in next week I'll restart the jobs of awesome-iOS including this integrations and miscellaneous things.

**Comment by onix-dolzhenko** [comment]
Hello guys! May be it would be cool to make an issue where other contributors could add Swift projects not written on Swift 3?

**Comment by dkhamsing** [comment]
We can use this one 
Will update

**Comment by bobbyarcher** [comment]
WYMaterialButton is not written on Swift 3. I just opened an issue asking if they were planning on updating it. (Sorry if this is the wrong place to put this!)

**Comment by dkhamsing** [comment]
@bobbyarcher thx!

**Comment by shubh10** [comment]
@dkhamsing instead of removing outdated projects from the list can we only remove the 🔶, maybe leave it empty or assign one symbol for latest version of swift and another symbol for old versions.

**Comment by dkhamsing** [comment]
No I think we do want to remove outdated projects

**Comment by shubh10** [comment]
Okay.

**Comment by dkhamsing** [comment]
Are you interested in helping 😊

**Comment by shubh10** [comment]
Sure, whatever I could do :)

**Comment by dkhamsing** [comment]
Well, we have a lot of issues and they might be easier to tackle since this is a rather large one
https://github.com/vsouza/awesome-ios/issues  

Please take a look!

**Comment by dkhamsing** [comment]
a big thanks to @lfarah for removing a lot of outdated libs 🎉 🎉🎉

**Comment by lfarah** [comment]
Thanks @dkhamsing! I was visiting @vsouza and we did this together!

**Comment by shubh10** [comment]
Found some outdated libs:

- [Kommander-iOS](https://github.com/intelygenz/Kommander-iOS)
- [Colors](https://github.com/paulot/Colors)
- [CostumeKit](https://github.com/jakemarsh/CostumeKit)
- [Safe](https://github.com/tidwall/Safe)
- [flowerchart](https://github.com/drinkius/flowerchart)
- [swiftydb](https://github.com/Oyvindkg/swiftydb)
- [PredicateEditor](https://github.com/arvindhsukumar/PredicateEditor)

Will wait for few days, then recheck and remove these from listing.

**Comment by lfarah** [comment]
@shubh10 thanks for taking time for this! I am removing almost all of them right now, but some of the libs you pointed out were updated

**Comment by lfarah** [comment]
I couldn't find any other projects that are not compatible with Swift 3. Closing this, but anyone feel free to reopen
