### ISSUE TITLE
Link star counts

### ISSUE THREAD

**Issue by burhanuddin353** [vsouza/awesome-ios#1130]
This would be great feature you could add to the README.md. Show star counts for each repository.

You can take help of this
https://github.com/ColinEberhardt/awesome-stars

**Comment by lfarah** [comment]
Hey @burhanuddin353, we already discussed in #1093, the ```README``` would become too confusing if we add the stars for every single library. What I thought that was interesting was yopur ** updating redirected URLs** feature. Can you talk more about it?

@dkhamsing would this be interesting for your ReadkeCritic?

**Comment by dkhamsing** [comment]
Uh not at the moment
