### ISSUE TITLE
Bump minimum version to iOS 9

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#1198]
I just checked [Apple's Developer Website](https://developer.apple.com/support/app-store/) and 92% of the iOS devices are using iOS 9 and up.
<img width="327" alt="screen shot 2016-10-24 at 7 02 19 pm" src="https://cloud.githubusercontent.com/assets/6511079/19670499/8c2a990c-9a1c-11e6-90da-b60c3670babd.png">

I think it would be better if we accepted iOS 9 and up.

What do you guys think? 🤔

**Comment by victorgama** [comment]
LGTM 🙌

**Comment by lfarah** [comment]
* [x] Me
* [x] @vsouza 
* [x] @victorgama
* [ ] @dkhamsing

**Comment by azawawi** [comment]
+1 for iOS 9+

I am also seeing problems on iOS 8.1 simulators during an `xcodebuild test` which I do not think Apple is going to fix anytime soon.

This also confirms it:
https://david-smith.org/iosversionstats/

**Comment by naeemshaikh90** [comment]
Yes its time to drop iOS 8!

**Comment by azawawi** [comment]
Any update on this one?

**Comment by vsouza** [comment]
I believe we had enough positive feedback to validate the change. Thank you all.

**Comment by dkhamsing** [comment]
@lfarah you should update https://github.com/vsouza/awesome-ios/blob/master/.github/PULL_REQUEST_TEMPLATE.md also :)

**Comment by azawawi** [comment]
Hooray! :+1:
