### ISSUE TITLE
UIViewPropertyAnimator Category

### ISSUE THREAD

**Issue by naeemshaikh90** [vsouza/awesome-ios#1208]
I want to add `SaveTheDot` game code using iOS 10's `UIViewPropertyAnimator`, where should I add this? or to create a sub category in `UI` ?

**Comment by lfarah** [comment]
@naeemshaikh90 can you send me the link so I can take a look at it?

**Comment by naeemshaikh90** [comment]
@lfarah https://github.com/JakeLin/SaveTheDot/issues

**Comment by lfarah** [comment]
Hmmmm, unfortunately SaveTheDot is not a library.

It would fit better into @dkhamsing's [Open source iOS apps](https://github.com/dkhamsing/open-source-ios-apps) list and I believe it is already there.

**Comment by naeemshaikh90** [comment]
That would be better.
