### ISSUE TITLE
Location library recommendation

### ISSUE THREAD

**Issue by robyzhou** [vsouza/awesome-ios#122]
Hi, 
Please forgive me, cause I do not know which is the best way to recommend some library here, so I just created a issue here.

As to the Location related library, I would like to recommend the LocationManager (https://github.com/intuit/LocationManager), it's really a awesome library to locate on iOS. 

Please take a look at that.

Thanks.

**Comment by vsouza** [comment]
@robyzhou nice lib :smile: 

Please read the [Contribution guide](https://github.com/vsouza/awesome-ios/blob/master/CONTRIBUTING.md) and send a pull request.

thanks.
