### ISSUE TITLE
RHSideButtons 

### ISSUE THREAD

**Issue by robertherdzik** [vsouza/awesome-ios#1235]
[RHSideButtons](https://github.com/robertherdzik/RHSideButtons) Library provides easy to implement variation of Android (Material Design) Floating Action Button for iOS. You can use it as your app small side menu.

**Comment by lfarah** [comment]
Hey @robertherdzik, thanks for contributing to AwesomeiOS! 👍 

Your library seems really cool and it makes it easy to implement a really nice set of buttons.

Before Adding it to AwesomeiOS, I need you [to fix this issue](https://github.com/robertherdzik/RHSideButtons/issues/7)

**Comment by robertherdzik** [comment]
Ok, guys now RHSideButtons lib meets all requirements related with installation 🍭

**Comment by lfarah** [comment]
Perfect!
