### ISSUE TITLE
Linking for "..need you to fix this issue"

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#1238]
@lfarah, all, please link from the issue (created) on the repo to our issue/pull so we can see the status from our side, rather than go to the other side

Example:
https://github.com/vsouza/awesome-ios/issues/1235

Thx

**Comment by dkhamsing** [comment]
@lfarah 
Feel free to close when you have read this

**Comment by lfarah** [comment]
@dkhamsing makes total sense! I always hated having to check the issue every time and never thought about a solution for this! 👍
