### ISSUE TITLE
Add AwesomeiOS Weekly Newsletter

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#1263]
Soooo, I'm so excited to talk about this!

#### About 👍
It's been almost an year since I've been talking with @vsouza about creating an AwesomeiOS Newsletter. Our plan is to have a weekly newsletter that showcases quality iOS libraries, frameworks and other iOS developer tools.
I decided to create this because I'm a big newsletter fan because they always provide amazing new links.

#### Content 🚀
* The Newsletter's content would be generated by filtering libs by their quality index, provided by CocoaPods + CocoaDocs.
* I would then write a small comment about each library.
* Each email contains an introduction paragraph and 10 links

#### Reasons ✅
* AwesomeiOS has been the same for the past 2 years, so we want to grow the project and connect more with our thousands of visitors.
* The project became too big for someone to go learn about new libraries, so instead of having thousands of libraries in one page, a Newsletter would only show 10.

**Comment by vsouza** [comment]
![giphy](https://cloud.githubusercontent.com/assets/484656/20498309/cea83fa2-b013-11e6-8ff0-248c3bb5a197.gif)

**Comment by naeemshaikh90** [comment]
Simply awesome!

**Comment by yoha** [comment]
@lfarah bravo! I assume the amount of stars / forks will determine the weekly selection of 10 libs?

**Comment by lfarah** [comment]
@yoha [take a look on how CocoaPods defines the quality index](https://guides.cocoapods.org/making/quality-indexes.html)

**Comment by naeemshaikh90** [comment]
On which day of week you're planning to send newsletter?
and I am ready for contribution on newsletter, feel free to contact me.

**Comment by lfarah** [comment]
Hey @naeemshaikh90, I finished writing the first edition today at 4:30am. We're planning on launching on Tuesday.

As for contributions, I'll talk to you! 😉

**Comment by natalia-osa** [comment]
I don't like email newsletters. Is there an option to subscribe RSS?

**Comment by lfarah** [comment]
Hey @natalia-osa, we're working on a website for AwesomeiOS.Weekly and we will provide RSS subscription. I'll let you know when we launch it! 👍

**Comment by lfarah** [comment]
Hey @natalia-osa, our website is finally out! http://weekly.awesomeios.com/

**Comment by dkhamsing** [comment]
Great work buddy, how does the quality index work

**Comment by natalia-osa** [comment]
Great work! What is the RSS address because I can't find it?

**Comment by vsouza** [comment]
@dkhamsing I'm working on a service to get from cocoa pods quality index API 😄

**Comment by lfarah** [comment]
Hey @natalia-osa. We don't support RSS yet. What you can do is to [follow this blog post](http://www.gyford.com/phil/writing/2014/02/12/email-to-rss-feed.php) and create a Zapier workflow that does email to RSS for you
