### ISSUE TITLE
Add Objective-CLI Obfuscator

### ISSUE THREAD

**Issue by karek314** [vsouza/awesome-ios#1277]
Hi,
May be worth to add
https://github.com/karek314/Objective-C-CLI-Obfuscator

It's simple Obj-C CLI Obfuscator with simple instructions, it contains branch to trick Apple Review since they are now more strict about "obfuscated" symbols, which is pretty dump when code is still readable since it's still cocoa.

**Comment by lfarah** [comment]
Hey @karek314, I talked to you on the PR. Closing this
