### ISSUE TITLE
New swift library - CRNetworkButton

### ISSUE THREAD

**Issue by vladdmitriev** [vsouza/awesome-ios#1282]
Hello,

How could I add our new library (https://github.com/Cleveroad/CRNetworkButton) to your site - http://ioslibraries.co/index.php/home
![demo_ 2](https://cloud.githubusercontent.com/assets/20402305/20596310/8b8d58e4-b246-11e6-8476-3de9322d154e.gif)

Can you help me?

**Comment by naeemshaikh90** [comment]
@vladdmitriev This library is already added in the list. In case you want to add another library you can submit a pull request.

**Comment by vladdmitriev** [comment]
@naeemshaikh90 Sorry I have not noticed it. Thank you!

**Comment by vladdmitriev** [comment]
@naeemshaikh90  Could you help me once more? Here is our library too - https://github.com/Cleveroad/CRRulerControl

![demo ruler](https://cloud.githubusercontent.com/assets/20402305/20601932/c18323e4-b263-11e6-968c-5fb7b341d2bb.gif)

In what category could I submit it? Maybe in "image"?

**Comment by lfarah** [comment]
Hey @vladdmitriev, thanks for contributing to AwesomeiOS and good job on the GIFS of your library. They look really legit!
Just a heads up: AwesomeiOS is not involved with [iOS Libraries.co](http://ioslibraries.co/index.php/home). They just use our information

**Comment by lfarah** [comment]
Thanks @naeemshaikh90 for helping out!!
