### ISSUE TITLE
Whitelist IBM Swift Sandbox

### ISSUE THREAD

**Issue by victorgama** [vsouza/awesome-ios#1303]
We should either whitelist or remove it, since it will keep redirecting the bot from `https://swiftlang.ng.bluemix.net/#/repl` to `https://swiftlang.ng.bluemix.net/verify`.

@dkhamsing Could you kindly check this out? Lets make `awesome_bot` stop screaming at us and worrying contributors 🙌

**Comment by dkhamsing** [comment]
yes yes 😅

**Comment by naeemshaikh90** [comment]
Yes @ifarah and we just discussing about this😂

**Comment by victorgama** [comment]
@dkhamsing Thank you! 🦄
