### ISSUE TITLE
vCard parser

### ISSUE THREAD

**Issue by viral-etymon** [vsouza/awesome-ios#1315]
Hi,

Is there any other library in swift which allow user to parse from vCard to Contact?

I konw there is inbuilt vCard parser from iOS but it is not upto mark. means it is not able to distingues between home|work phone number, home|work address etc.

Regards

**Comment by lfarah** [comment]
@viral-etymon I wasn't able to find any libraries, but [I found this](https://github.com/tkareine/VCardImport)

**Comment by lfarah** [comment]
@viral-etymon apparently we found you an answer. Please take a look at the PR above
