### ISSUE TITLE
I  created two repositories. please add them

### ISSUE THREAD

**Issue by sxyx2008** [vsouza/awesome-ios#135]
I  created two repositories

[awesome-ios-animation](https://github.com/sxyx2008/awesome-ios-animation) about iOS Animation Libraries.

[awesome-ios-chart](https://github.com/sxyx2008/awesome-ios-chart) about iOS Chart Libraries.

Thanks

**Comment by vsouza** [comment]
please read the [Contribution Guide](https://github.com/vsouza/awesome-ios/blob/master/CONTRIBUTING.md) and send your pull requests.
