### ISSUE TITLE
Animations and Modal Transitions

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#1423]
Should transitions go under animations ?
Also some animations projects might belong to transitions

**Comment by vsouza** [comment]
What u think @lfarah ?

**Comment by lfarah** [comment]
Hmmmmmm....
I'm not 100% good with the idea, but yeah, transitions should go under animations. Maybe change the title to "Transitions" instead of "Modal Transitions" too

**Comment by dkhamsing** [comment]
Let's do it
