### ISSUE TITLE
Add collaborators 

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#1464]
@vsouza @lfarah @victorgama 
 
Hey guys with the volume of pull requests, do you think we should add new collaborators? Any suggestions?

**Comment by vsouza** [comment]
I agree. I suggest @nschucky and @miguelarauj1o

**Comment by lfarah** [comment]
@naeemshaikh90 has been pretty active lately, answering people's PRs and sending out a lot of stuff

**Comment by lfarah** [comment]
Sorry guys, I used to be more active.... It has been hard to work a lot on Awesome since I came back to Brazil, taking a lot of freelance projects

**Comment by dkhamsing** [comment]
It's ok
We're happy with any time you can give to this project :)

**Comment by dkhamsing** [comment]
@vsouza can you give access to @nschucky and @naeemshaikh90 ?
 
@miguelarauj1o pls leave us a message if you have time to help us manage the repo

**Comment by vsouza** [comment]
Wait, wait. And the ritual for new members?  😆

**Comment by vsouza** [comment]
@nschucky and @naeemshaikh90 check your mailbox. Welcome ❤️

**Comment by dkhamsing** [comment]
@lfarah maybe we can write up something for Collaborators.. just basic stuff. In a gist or wiki?

**Comment by miguelarauj1o** [comment]
I can help you guys. Count me on!

**Comment by nschucky** [comment]
@dkhamsing that would be great!

**Comment by lfarah** [comment]
@dkhamsing what about a `Collaborators.md`, so it stays in the repo?

**Comment by vsouza** [comment]
@miguelarauj1o check your mailbox.
