### ISSUE TITLE
HxSTLParser

### ISSUE THREAD

**Issue by victorgama** [vsouza/awesome-ios#1469]
Some time ago I created a (somewhat basic) STL loader for SceneKit.
Although we still don't have any SceneKit-related projects (AFAIK), it may be a nice start point for someone who wants to load STL files into SceneKit. ✨ 

It's currently used by the [Aura Project](https://loveproject.com.br), and the source is available at [victorgama/HxSTLParser](https://github.com/victorgama/HxSTLParser).

What you guys think?

> @lfarah: You usually have great feedbacks on Readmes. I'd _really_ appreciate if you have any. 🙌

**Comment by dkhamsing** [comment]
@victorgama the readme looks pretty good :)

**Comment by victorgama** [comment]
@dkhamsing Thanks! ✨

**Comment by lfarah** [comment]
Hey @victorgama, nice README! I'll open a couple issues over there

**Comment by vsouza** [comment]
@victorgama still in doubt with classification?

**Comment by victorgama** [comment]
@vsouza Yeah... Maybe Graphics? 🤔

**Comment by vsouza** [comment]
@victorgama Yes. Would be nice.
