### ISSUE TITLE
Handle Multiple Stanford's CS193p iTunes Courses

### ISSUE THREAD

**Issue by naeemshaikh90** [vsouza/awesome-ios#1471]
We have multiple iOS version supported Stanford's CS193p courses, do we need to keep them all from iOS 7 to iOS 10? or just the latest one?

iOS 7 course supports Objective-C
iOS 8 - 10 courses supports respective Swift versions.

IMHO we should keep iOS 7(Objective-C) and iOS 10(Swift).

What you think guys? @lfarah , @dkhamsing , @vsouza

**Comment by lfarah** [comment]
@naeemshaikh90's argument on keeping the iOS 7 version is that it was the last one teaching `Objective-c`. I agree with him on keeping iOS 7 and iOS 10 courses, removing the rest of them

**Comment by naeemshaikh90** [comment]
Ok so we would keep iOS 7(Objective-C) and iOS 10(Swift) Stanford's CS193p courses.

**Comment by naeemshaikh90** [comment]
Done, [Remove old courses](https://github.com/vsouza/awesome-ios/commit/333f3df453d36396d2a4625009ef0724ced2d292), [Add iOS 7 course]( https://github.com/vsouza/awesome-ios/commit/3da62ebf7e9a58f42998f7a0c644c406edfdbfad)
