### ISSUE TITLE
Broken Link in README : `UI` / `Animation` / `Transition` - 404

### ISSUE THREAD

**Issue by sushihangover** [vsouza/awesome-ios#1483]
In main index/outline: 

`UI` / `Animation` / `Transition` hyperlink  goes to https://github.com/vsouza/awesome-ios/blob/master/transition (404 result)

![screen shot 2017-02-19 at 4 04 42 am](https://cloud.githubusercontent.com/assets/1294194/23102157/ad9a1214-f658-11e6-86ec-9441b1ea466a.png)

**Comment by nschucky** [comment]
thanx a lot @sushihangover

**Comment by miguelarauj1o** [comment]
Fixed by @nschucky
