### ISSUE TITLE
I recommend a powerful iOS View Layout framework

### ISSUE THREAD

**Issue by youngsoft** [vsouza/awesome-ios#1494]
iOS: [https://github.com/youngsoft/MyLinearLayout](https://github.com/youngsoft/MyLinearLayout)

swift: [https://github.com/youngsoft/TangramKit](https://github.com/youngsoft/TangramKit)

**Comment by vsouza** [comment]
@youngsoft thanks for your tip. Could you create a pull request?

**Comment by nschucky** [comment]
I'm gonna create the PR's, thanx

**Comment by naeemshaikh90** [comment]
#1560
