### ISSUE TITLE
The awesomeios.com page isn’t working

### ISSUE THREAD

**Issue by arasu01** [vsouza/awesome-ios#1517]
I just tried to open http://awesomeios.com and found that it's not working (PFA). 
![screen shot 2017-03-02 at 9 58 50 am](https://cloud.githubusercontent.com/assets/6689319/23493050/010add6e-ff2f-11e6-9f9a-cdf81f93a43b.png)

**Comment by lfarah** [comment]
Hey @arasu01, thanks for pointing that out. @vsouza is working on it
