### ISSUE TITLE
Classification for library 

### ISSUE THREAD

**Issue by terflogag** [vsouza/awesome-ios#1526]
Hello,

I can't find the good section for this library : https://github.com/terflogag/OpenSourceController

Any idea ? 
Thank you !

**Comment by lfarah** [comment]
Hey @terflogag,
Your lib is similar to [EasyAbout](https://github.com/JARMourato/EasyAbout).
Please add it under [/Utility](https://github.com/vsouza/awesome-ios#utility)

Thanks for contributing 👍 🎉

**Comment by terflogag** [comment]
Cool ! I didn't know this library, thank you 👍
