### ISSUE TITLE
QuietModemKit Category

### ISSUE THREAD

**Issue by naeemshaikh90** [vsouza/awesome-ios#1546]
I which category should we add this ?🤔
https://github.com/quiet/QuietModemKit

@dkhamsing @lfarah

**Comment by lfarah** [comment]
Shit... This is so different from everything.... [/Other Hardware\(https://github.com/vsouza/awesome-ios#other-hardware)?

**Comment by dkhamsing** [comment]
How about Audio

**Comment by nschucky** [comment]
I think it should go in the Audio category as well

**Comment by naeemshaikh90** [comment]
Ok than we should go with the Audio category.
