### ISSUE TITLE
set-simulator-location

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#1586]
Is this lib under /Tools or under /Location?

[set-simulator-location](https://github.com/lyft/set-simulator-location) - CLI for setting location in the iOS simulator

**Comment by dkhamsing** [comment]
let's go with Location

**Comment by miguelarauj1o** [comment]
I think it's better under location.

**Comment by nschucky** [comment]
everyone agrees with going under Location? can we close?

**Comment by dkhamsing** [comment]
let's close when the project is added

**Comment by nschucky** [comment]
#1644
