### ISSUE TITLE
API Category

### ISSUE THREAD

**Issue by Daltron** [vsouza/awesome-ios#1598]
This category would include libraries that help make accessing web API's easier on iOS. Two libraries that I have created that would fit perfectly into this category are:

[BigBoard](https://github.com/Daltron/BigBoard) - An Elegant Financial Markets Library Written in Swift
[Spartan](https://github.com/Daltron/Spartan) - An Elegant Spotify Web API Library Written in Swift for iOS and macOS

I'm sure there are many other libraries that could fit perfectly into this category as well.

**Comment by dkhamsing** [comment]
How about SDK?

**Comment by Daltron** [comment]
@dkhamsing You are correct. Based on other repos in that section, the two mentioned above would fit in there. Thanks!
