### ISSUE TITLE
Deleting Projects

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#1641]
Let's come up with some guidelines for removing projects

- no updates / no longer works
- deprecated
- lacking license 

what else?

@vsouza @lfarah @naeemshaikh90 @miguelarauj1o 

After that

- [x] update https://github.com/vsouza/awesome-ios/blob/master/.github/CONTRIBUTING.md
- [x] address #1640

**Comment by victorgama** [comment]
I think it would be nice to pay attention to projects lacking a license.
We may notify current repositories that they lack a license (and in the future, take action), and also instruct authors of new contributions of that, taking them to https://choosealicense.com/ ✨ 

Quoting the _Choose a License_ website:

> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

**Comment by dkhamsing** [comment]
Good idea

**Comment by dkhamsing** [comment]
This should apply for adding projects as well

**Comment by victorgama** [comment]
Yep!
> (...)  and also instruct authors of new contributions of that

**Comment by dkhamsing** [comment]
For #1640

Seems the library is still fairly new, let's leave it for now
