### ISSUE TITLE
Rename projects

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#1654]
Some projects have been renamed recently and we have to update our list

https://github.com/vsouza/awesome-ios/commit/3fccc9eacd7960a76023c64716010e9d434fec33
https://github.com/vsouza/awesome-ios/commit/d00be8f7655cbff76845184cd2785fdece9f7410

**Comment by dkhamsing** [comment]
@victorgama 
thanks for looking into this
there are 10 projects total to rename, not sure you got them all

**Comment by victorgama** [comment]
@dkhamsing Oh gosh! My bad. Sorry about that.

**Comment by victorgama** [comment]
Okay, now they're gone. ✨
