### ISSUE TITLE
www.ioscreator.com down

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#1688]
let's remove or close this issue on Jun 1

https://www.ioscreator.com/

**Comment by victorgama** [comment]
Any idea how long is it down? Was iterating through some redirects today and stumbled on errors caused by iOSCreator on Travis. 🤔

**Comment by dkhamsing** [comment]
not sure.. new problem I think ?

**Comment by victorgama** [comment]
Probably. Last commit on @ioscreator's repository was 14 days ago.
Let's wait and remove (or hopefully, just close this one).

🙌

**Comment by miguelarauj1o** [comment]
I'm closing this issue because **iOScreator** is back.
Feel free to reopen if you want to.
