### ISSUE TITLE
React-like Frameworks Category

### ISSUE THREAD

**Issue by s4cha** [vsouza/awesome-ios#1741]
Hello,

Looking at it now, react-like frameworks are somewhat lost in RXExtensions at the moment.
Indeed they have nothing to-do with reactive programming per-se (observables etc.)

I really believe we could have a separate Category for **React-like** Frameworks.

It would gather :

[Render](https://github.com/alexdrone/Render)
[Katana](https://github.com/BendingSpoons/katana-swift)
[TemplateKit](https://github.com/mcudich/TemplateKit)
[Komponents](https://github.com/freshOS/Komponents)

Also ([Few.swift](https://github.com/joshaber/Few.swift), [Reactant](https://github.com/Brightify/Reactant), not yet on awesome-ios)

What do you think?

---

TODO:
* [x] create React-Like Frameworks under Reactive Programming
* [x] move libraries above there
* [x] Add Few.swift and Reactant

**Comment by dkhamsing** [comment]
@s4cha can we put this new section under "Reactive Programming" ?

**Comment by s4cha** [comment]
@dkhamsing You mean a sub section ? Cause these are already in the "Reactive Programming" section.

**Comment by dkhamsing** [comment]
yes sub section

**Comment by s4cha** [comment]
Sure then :)

**Comment by lfarah** [comment]
@s4cha I can add [Reactant](https://github.com/Brightify/Reactant) but I cannot add [Few.swift](https://github.com/joshaber/Few.swift) because it is not written in Swift 3

**Comment by s4cha** [comment]
Awesome! Cheers
