### ISSUE TITLE
Request for Bluetooth Section?

### ISSUE THREAD

**Issue by rlam3** [vsouza/awesome-ios#179]
Is there any good bluetooth resources/libraries that we should be aware of?

**Comment by dkhamsing** [comment]
Check these out
- https://github.com/omergul123/Discovery
- https://github.com/l0gg3r/LGBluetooth
- https://github.com/ohwutup/OWUProximityManager

Also this one
- https://github.com/jpsim/PeerKit

**Comment by rlam3** [comment]
Thanks! But I'm looking for swift library or cocoapod framework to help me detect devices and stream audio to another bluetooth device... Do you know of any code examples/repos?

**Comment by dkhamsing** [comment]
Only the above

**Comment by lfarah** [comment]
@rlam3 http://stackoverflow.com/questions/30722810/stream-audio-from-microphone-via-bluetooth-to-another-iphone

**Comment by dkhamsing** [comment]
https://github.com/lauraskelton/simple-share
