### ISSUE TITLE
Heavy signature injection：github.com/codesourse/iInjection

### ISSUE THREAD

**Issue by codesourse** [vsouza/awesome-ios#1799]
iInjection is developed by codesourse https://github.com/codesourse

This is an app for OS X that can inject dylib and (re)sign apps and bundle them into ipa files that are ready to be installed on an iOS device.

Supported input types are: ipa, deb, app, xcarchive

Usage

This app requires Xcode to be installed, it has only been successfully tested on OS X 10.11 at this time.

You need a provisioning profile and signing certificate, you can get these from Xcode by creating a new project.

You can then open up iOS App Signer and select your input file, signing certificate, provisioning file, and optionally specify a new application ID and/or application display name.

**Comment by lfarah** [comment]
Hey @codesourse, thanks for opening the issue! Can you give us a real world example on where this lib would be used?

**Comment by codesourse** [comment]
![image](https://user-images.githubusercontent.com/6462119/29015130-54333c08-7b7f-11e7-83fa-1a250216fbb0.png)

Has been in application instructions

**Comment by dkhamsing** [comment]
I thought no we’ll pass, feel free to reopen @lfarah
