### ISSUE TITLE
Update MessageKit

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#1808]
#1807 

Original project was deleted 
https://github.com/MessageKit/MessageKit-iOS  
Now up at 
 https://github.com/MessageKit/MessageKit

**Comment by dkhamsing** [comment]
and it's back https://github.com/MessageKit/MessageKit 🤔

**Comment by dkhamsing** [comment]
Uh we have to rename it

**Comment by dkhamsing** [comment]
@shubh10 if you want to help 😄

**Comment by shubh10** [comment]
fixed it - [#1818](https://github.com/vsouza/awesome-ios/pull/1818)
