### ISSUE TITLE
Router

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#1838]
[Router](https://github.com/freshOS/Router) - 🛣 Simple Navigation for iOS :large_orange_diamond:

**Comment by serhii-londar** [comment]
Hi @lfarah ! 
You can move this to "URL Scheme" category. Or create new category "App Routing" or "App navigation". Also, you can move [Marshroute](https://github.com/avito-tech/Marshroute), [JLRoutes](https://github.com/joeldev/JLRoutes) and [SwiftRouter](https://github.com/skyline75489/SwiftRouter)  library to this category.

**Comment by dkhamsing** [comment]
I would vote for App Routing

**Comment by serhii-londar** [comment]
Issue fixed in #2099.
