### ISSUE TITLE
Skeleton

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#1839]
[Skeleton](https://github.com/gonzalonunez/Skeleton) - An easy way to create sliding CAGradientLayer animations! Works great for creating skeleton screens for loading content. :large_orange_diamond:

**Comment by aaronjsutton** [comment]
#2104

**Comment by dkhamsing** [comment]
What category should it go to? Animation doesn’t seem right 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aaronjsutton** [comment]
@dkhamsing Activity Indicator may be a better fit, since it seems to be applied mostly to loading content.
