### ISSUE TITLE
Add emoji "🛑" indicating "Library is no longer supported"

### ISSUE THREAD

**Issue by mixdesign** [vsouza/awesome-ios#1897]
For what community **use** Awesome-ios for?
We do **search** for a thing we need!
When we search, we select the best and suitable.

Therefore, it would be very convenient to pre-warn users which library is no longer supported and stopped receiving updates. 
Using emoji "🛑" this way:
> Of course, we can replace the icon with some other one.

![not-supported](https://user-images.githubusercontent.com/198882/29003783-20586386-7adf-11e7-9af0-f21102d6294f.png)

**Comment by lfarah** [comment]
Hey @mixdesign, I spent a couple days last week removing unsuported libraries. Instead of adding a 🛑 emoji, I think it's best to remove it from AwesomeiOS

**Comment by dkhamsing** [comment]
Right
If it's no longer supported, it would be removed

**Comment by mixdesign** [comment]
@lfarah I agree! Can [awesome_bot](https://github.com/dkhamsing/awesome_bot) do that for you @dkhamsing?

**Comment by dkhamsing** [comment]
Not at the moment
