### ISSUE TITLE
'FAPanels' should be in menu section

### ISSUE THREAD

**Issue by fahidattique55** [vsouza/awesome-ios#1905]
Summary:
Move `FAPnels` to *Menu*

*edited*

---

Hey there,

I own the 'FAPanels' repository. I think it would be more easy for users to find FAPanels under 'menu' rather that 'Transitions'. I suggest, It should something like this,

"FAPanels - "Side menu library with interactive and custom transitions"

Thanks & Regarsd

**Comment by dkhamsing** [comment]
Will update, thanks!

**Comment by lfarah** [comment]
Hey @fahidattique55, thanks for letting us know. It is fixed!
