### ISSUE TITLE
RNCryptor - a popular Encryption (Security) framework

### ISSUE THREAD

**Issue by Mylittleswift** [vsouza/awesome-ios#1957]
[RNCryptor](https://github.com/RNCryptor/RNCryptor) - (AES encryption) wrappers for iOS and Mac in Swift. -- For ObjC, see RNCryptor/RNCryptor-objc

**Comment by lfarah** [comment]
@dkhamsing what do you think?

**Comment by dkhamsing** [comment]
Looks good

**Comment by lfarah** [comment]
@Mylittleswift please open a PR. Let me know if you need any help

**Comment by Mylittleswift** [comment]
pull requested, please review and approve.
