### ISSUE TITLE
LNPopupController - an awesome Popup (UI) framework

### ISSUE THREAD

**Issue by Mylittleswift** [vsouza/awesome-ios#1958]
[LNPopupController](https://github.com/LeoNatan/LNPopupController) is a framework for presenting view controllers as popups of other view controllers, much like the Apple Music and Podcasts apps.

**Comment by lfarah** [comment]
Hey @Mylittleswift, this lib is awesome. Please open a PR adding it!

**Comment by dkhamsing** [comment]
https://github.com/vsouza/awesome-ios/pull/1986

**Comment by LeoNatan** [comment]
Thanks or the support!
