### ISSUE TITLE
nsrails - intuitive integration with a rest api

### ISSUE THREAD

**Issue by dadleyy** [vsouza/awesome-ios#199]
I've been using [nsrails](https://github.com/dingbat/nsrails) to integrate my ios app with a mvc rest api and have been having an amazing time with it. Here's some code using it:

```
NSRRequest *req = [NSRRequest requestToFetchAllObjectsOfClass:[DevicePermission class]];
[req setQueryParameters:@{@"user":[[self user] pk]}];
[req sendAsynchronous:^(id json, NSError *error) {
    if(error) return;
    [[self permissions] addObjectsFromArray:[DevicePermission objectsWithRemoteDictionaries:json]];
}];
```

Its really nice because developers define objective-c classes that act exactly like orm models. Think its a good fit for this list? (I'm not a contributor to the library)

**Comment by victorgama** [comment]
Looks good! Feel free to send a PR. :shipit:
