### ISSUE TITLE
Please check my repo

### ISSUE THREAD

**Issue by EvgenyKarkan** [vsouza/awesome-ios#205]
Hi!
I created repository with well known algorithms and data structures implemented in ObjC.
https://github.com/EvgenyKarkan/EKAlgorithms
Hope it will be useful for your repo ;)
Thanks

**Comment by dkhamsing** [comment]
Pretty cool 
@victorgama where should it go?

**Comment by victorgama** [comment]
@dkhamsing I think we can categorise it as Utility, given `underscore.m` is also there. What you think?

**Comment by dkhamsing** [comment]
Sounds good

**Comment by EvgenyKarkan** [comment]
Thank you guys & have a nice day!
Best wishes
