### ISSUE TITLE
Help wanted: call for collaborators 

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#2089]
Let's find more people to help with `awesome-ios`

Do you have any suggestions? Please leave a comment and use the reactions, thanks

@vsouza @lfarah

**Comment by dkhamsing** [comment]
I nominate @arasu01 https://github.com/vsouza/awesome-ios/pulls?q=is%3Apr+author%3Aarasu01

**Comment by jack3010** [comment]
I wanna collaborator for awesome-ios.

**Comment by Yogesh-MV** [comment]
I am interested in awesome-ios collaborator. Let me know how can I help?

**Comment by arasu01** [comment]
@dkhamsing: Thanks for nominating me. I'm really interested in it.

**Comment by lfarah** [comment]
Sorry guys, been busy in the past weeks but I should be able to organize myself to contributing more in the next 2 weeks. But definitely agree that we need more people

**Comment by dkhamsing** [comment]
No problem man, it’s all good

**Comment by serhii-londar** [comment]
HI @dkhamsing! I'm interested in collaboration. Can I help somehow?

**Comment by dkhamsing** [comment]
@serhii-londar hi, if you have time to contribute, please leave open pull requests to close issues we have, comment on pull requests to approve or make suggestions! that would be a great way to start

thanks

**Comment by aaronjsutton** [comment]
I am interested in becoming a collaborator. Happy to help in any way I can.

**Comment by lukecrum** [comment]
I am interested in becoming a collaborator. I can help in any way necessary

**Comment by dkhamsing** [comment]
@aaronjsutton @lukecrum  

hi, if you have time to contribute, please open pull requests to close issues we have, comment on pull requests to approve or make suggestions! that would be a great way to start

thanks
