### ISSUE TITLE
Remove libraries by Rob Nash

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#2092]
3 of his projects are now 404

**Comment by Yogesh-MV** [comment]
@dkhamsing I am interested in helping

**Comment by dkhamsing** [comment]
@Yogesh-MV can you open a pull request to remove Rob Nash libraries?
:)

**Comment by dkhamsing** [comment]
Line | Status | Link
| ---: | :----: | --- |
2197 | [404](https://httpstatuses.com/404) | https://github.com/rob-nash/CollapsableTable 
2217 | [404](https://httpstatuses.com/404) | https://github.com/rob-nash/PageFeedControl 
2256 | [404](https://httpstatuses.com/404) | https://github.com/rob-nash/CollapsibleTable

**Comment by serhii-londar** [comment]
Hi @dkhamsing . I've added pull request #2094 .

**Comment by Yogesh-MV** [comment]
@dkhamsing : Sorry I missed your comment because it was my night time.
@serhii-londar : Thanks for attending.
