### ISSUE TITLE
Rearrange Location, Other Hardware

### ISSUE THREAD

**Issue by Mylittleswift** [vsouza/awesome-ios#2118]
In context, [Location](#location) and [Other Hardware](#other-hardware) should follow up [iBeacon](#ibeacon) in [Hardware](#hardware) category, but they are actually after [Layout](#layout). Need to rearrange these two items to the right place.

**Comment by dkhamsing** [comment]
@arasu01 @serhii-londar can u guys help with the above if u have time?
