### ISSUE TITLE
Newsletter Status

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#2123]
@lfarah @vsouza 
hey guys is the newsletter active? on hiatus?

**Comment by vsouza** [comment]
@dkhamsing I was in vacation,but now I'm back. I'll talk with @lfarah to restart our work on newsletter. 😄

**Comment by arasu01** [comment]
@vsouza, @lfarah and @dkhamsing : Please let me know if you need my help on this.
