### ISSUE TITLE
It would be batter to remove deprecated / unsupported / unmaintained library 

### ISSUE THREAD

**Issue by indrajitsinh** [vsouza/awesome-ios#2153]
For an eg library like https://github.com/jessesquires/JSQMessagesViewController is officially deprecated by its author so it would be nice to clean up all other libraries as well that are deprecated/unsupported/unmaintained

**Comment by serhii-londar** [comment]
@vsouza @lfarah @dkhamsing 
We need some kind of a conditions to clean up repositories. Also I suggest to organize cleaning process by categories and save cleaned repositories in another list, f.e CLEANED.md.

**Comment by lfarah** [comment]
Hey @indrajitsinh, thanks for looking that up. I try to do a major clean up once in a while but it's hard to keep up with a list so long.
What we normally do is to [open a PR removing a deprecated library](https://github.com/vsouza/awesome-ios/search?q=removed&type=Issues&utf8=%E2%9C%93)

I agree with @serhii-londar that we need to organize a cleaning process by categories, but I don't think we should create another Markdown file.

What I think we should to is to open issues for all categories and we split to check for all o them. 

What do you all think about this?

**Comment by dkhamsing** [comment]
Deprecated libraries should just be removed from the list 

Not sure anyone has time to check all the projects on the list

f anything doesn’t look right, just open a pr to fix that particular project
