### ISSUE TITLE
Architecture Patterns category

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#2195]
@imJustik suggested in out Gitter channel that we should have an Architecture Patterns category. What do you guys think?

**Comment by lfarah** [comment]
@imJustik what repositories would fit in this category?

**Comment by dkhamsing** [comment]
Let’s make a list 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by serhii-londar** [comment]
We can start with this:
SwiftyVIPER - Makes implementing VIPER architecture much easier and cleaner. 🔶
CleanArchitectureRxSwift - Example of Clean Architecture of iOS app using RxSwift. 🔶
Viperit - Viper Framework for iOS. Develop an app following VIPER architecture in an easy way. Written and tested in Swift. 🔶
Reactant - Reactant is a reactive architecture for iOS 🔶

**Comment by dkhamsing** [comment]
@serhii-londar could you make a pull request for this issue ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by imJustik** [comment]
Thank you a lot :)

**Comment by lfarah** [comment]
Good job @serhii-londar!

**Comment by lfarah** [comment]
Good job @serhii-londar!
