### ISSUE TITLE
Remove Alcatraz

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#2211]
From https://github.com/alcatraz/Alcatraz

> Please note that plugins are not supported by Xcode 8

**Comment by dkhamsing** [comment]
@serhii-londar @arasu01 can you help? 🙏

**Comment by dkhamsing** [comment]
Actually maybe this should be removed??

**Comment by serhii-londar** [comment]
@dkhamsing How about **Plugins** subsection? Should we keep it?

**Comment by dkhamsing** [comment]
I think removing is correct - let me know if there’s a problem
