### ISSUE TITLE
Remove swiftnews 

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#2228]
https://swiftnews.curated.co/ Is now 404

**Comment by dkhamsing** [comment]
@arasu01 @serhii-londar can you help?

**Comment by dkhamsing** [comment]
Thx guys
Looks like that link appears twice (a mistake when added?)

So we have to remove the other one 

@arasu01 @serhii-londar

**Comment by serhii-londar** [comment]
@dkhamsing I'll check.
