### ISSUE TITLE
Remove :large_orange_diamond:

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#2244]
@vsouza and I were talking about removing the :large_orange_diamond: (🔶) because Swift is too common nowadays for us to care about this.

What do you guys think about it?

**Comment by victorgama** [comment]
@lfarah LGTM, but do you intend to mark ObjC projects, as they now became exceptions?

**Comment by lfarah** [comment]
Hmmmm, I don't think so?

**Comment by victorgama** [comment]
Oh, I don't think it would. Just asking out of curiosity. :)

**Comment by victorgama** [comment]
23

**Comment by vsouza** [comment]
#2263

**Comment by dkhamsing** [comment]
Updated the reference to be from the pr instead 🙏
