### ISSUE TITLE
add CreditCardForm to Payments 

### ISSUE THREAD

**Issue by orazz** [vsouza/awesome-ios#2315]
https://github.com/orazz/CreditCardForm-iOS

**Comment by vsouza** [comment]
@orazz Thanks for the suggestion. The @serhii-londar sent a pull request with your suggestion and we merged. 

At the next time you could send a pull request with your suggestion according our [Contribution Guidelines](https://github.com/vsouza/awesome-ios/blob/master/.github/CONTRIBUTING.md). 😃
