### ISSUE TITLE
Add some content that do not have specific category listed

### ISSUE THREAD

**Issue by miguelarauj1o** [vsouza/awesome-ios#232]
Hey, some repositories I do not know where is the right place to include or I believe that does not have a category. See below:

- [x] [ObjectiveSugar](https://github.com/supermarin/ObjectiveSugar)
- [ ] [Atlas-iOS](https://github.com/layerhq/Atlas-iOS)
- [x] [ResearchKit](https://github.com/ResearchKit/ResearchKit)
- [x] [MotionKit] (https://github.com/MHaroonBaig/MotionKit)
- [x] [IntentKit](https://github.com/intentkit/IntentKit)
- [ ] [HockeyKit](https://github.com/bitstadium/HockeyKit)
- [x] [FontAwesomeKit](https://github.com/PrideChung/FontAwesomeKit)
- [ ] [canabalt-ios](https://github.com/ericjohnson/canabalt-ios)
- [x] [GroundControl](https://github.com/mattt/GroundControl)
- [x] [JSPatch](https://github.com/bang590/JSPatch)
- [x] [Reader](https://github.com/vfr/Reader)
- [x] [JLRoutes](https://github.com/joeldev/JLRoutes)
- [x] [BEMSimpleLineGraph](https://github.com/Boris-Em/BEMSimpleLineGraph)
- [x] [tapkulibrary](https://github.com/devinross/tapkulibrary)
- [x] [XLForm](https://github.com/xmartlabs/XLForm)
- [ ] [Twin Prime](http://www.twinprime.com)
- [x] [PacketZoom](https://packetzoom.com)
- [x] [pop](https://github.com/facebook/pop)
- [x] [GPUImage](https://github.com/BradLarson/GPUImage)
- [ ] [Async](https://github.com/duemunk/Async)
- [ ] [Retini](https://github.com/terwanerik/Retini)
- [ ] [Blade](https://github.com/jondot/blade)
- [ ] [Watchdog](https://github.com/wojteklukaszuk/Watchdog)

**Comment by dkhamsing** [comment]
Facebook, DeepLink can go to SDK

**Comment by lfarah** [comment]
xctool can be added on "Other Xcode"

**Comment by miguelarauj1o** [comment]
true, deeplink and xctool removed. Thanks @dkhamsing and @lfarah

**Comment by lfarah** [comment]
FontAwesomeKit would enter in UI, since it deals with icons

**Comment by lfarah** [comment]
Same for BEMSimpleLineGraph

**Comment by lfarah** [comment]
JL Routes would fall into Networking

**Comment by lfarah** [comment]
It's not perfect, but IntentKit would go into Utility? 
I don't know about you guys, but this Framewor's main use for me would be in opening Maps apps, such as Google Maps and Waze, so it could also fall into maps. @dkhamsing what do you think?

**Comment by dkhamsing** [comment]
actually looks like intent kit is supposed to be like jlroutes or deeplink

**Comment by dkhamsing** [comment]
IntentKit can go to URL Scheme

**Comment by lfarah** [comment]
@vsouza @dkhamsing  Reader is inside Media and it's very similar to many image viewers [like this one](https://github.com/mollywoodnini/ImageViewer).
I just saw that the video section has only one item.
What if we put image + pdf + video inside a media section?

**Comment by lfarah** [comment]
[ResearchKit](https://github.com/ResearchKit/ResearchKit) inside SDK/Official??

**Comment by dkhamsing** [comment]
Yes and yes

**Comment by lfarah** [comment]
@miguelarauj1o I created a PDF section so you can add Reader inside.

**Comment by vsouza** [comment]
:clap:

**Comment by lfarah** [comment]
For Motionkit, I didn't want to create a Core Motion section because it's waay too especific. Do you guys see any other framework that would fit under a Hardware section?

**Comment by dkhamsing** [comment]
Hmm no but go for `Hardware`

**Comment by lfarah** [comment]
Hmmmm.. I don't like it. @vsouza any comments?

**Comment by lfarah** [comment]
@miguelarauj1o please add MotionKit to Hardware/CoreMotion

**Comment by lfarah** [comment]
@miguelarauj1o XLForm should go in UI

**Comment by lfarah** [comment]
@dkhamsing @vsouza ObjectiveSugar in Xcode/Plugins?!?!?!

**Comment by dkhamsing** [comment]
ObjectiveSugar should go to Utility

**Comment by vsouza** [comment]
GroundControl should go to Utility too

**Comment by vsouza** [comment]
We can create a category called "Misc" with projects like `JSPatch`

**Comment by dkhamsing** [comment]
@vsouza how about a dedicate section called `Bridging`

**Comment by vsouza** [comment]
@dkhamsing good idea!

**Comment by dkhamsing** [comment]
@miguelarauj1o please create a section called `Bridging` and add JSPatch to it, thanks :smile:

**Comment by lfarah** [comment]
This list is almost over! Thanks to @miguelarauj1o for bringing those awesome Libraries and @dkhamsing & @vsouza for trying to find a place for everything!

**Comment by miguelarauj1o** [comment]
thanks all you guys! This repository is awesome and extremely useful.

**Comment by miguelarauj1o** [comment]
another project added to the list above

**Comment by vsouza** [comment]
pop could enter the Animation category, if it is added. What do you think @lfarah ?

**Comment by dkhamsing** [comment]
let's put `tapkulibrary` in `UI`

**Comment by vsouza** [comment]
GPUImage has already been added.

**Comment by vsouza** [comment]
https://packetzoom.com can go to SDK's section

**Comment by dkhamsing** [comment]
Async can go to Utility

**Comment by lfarah** [comment]
We are separating this in different issues from now on. I discussed that with @vsouza
