### ISSUE TITLE
Main category description

### ISSUE THREAD

**Issue by vsouza** [vsouza/awesome-ios#2390]
Hi guys.

In last weeks I've been  looking for some layout improvements on awesome-ios. 

We growing a lot. We have a lot of categories, and the concerned about visual organization is very present. So, I'm proposing that each Main category should have an explanation about the content.

It's a one line straight forward description.
In clear language, without space for doubts about the category content.

What you think guys?

example: 

![screen shot 2018-02-21 at 1 48 16 pm](https://user-images.githubusercontent.com/484656/36493281-fdf08726-170d-11e8-83c2-4f393c4879d4.png)

**Comment by victorgama** [comment]
Looks great. Can even help contributors finding the right category for their libs. 👍

**Comment by lfarah** [comment]
Good idea!

**Comment by vsouza** [comment]
I'll update the categories with descriptions. Thanks guys.
