### ISSUE TITLE
META - removal of listing?

### ISSUE THREAD

**Issue by bbookman** [vsouza/awesome-ios#2431]
How do you wan't folks to request removal.  This one is like 5 years old 

CrashMonkey - Monkey Test Tool For iOS.

**Comment by dkhamsing** [comment]
Create a pull request pls 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vsouza** [comment]
The project was removed. Thanks for reporting @bbookman
