### ISSUE TITLE
Cleanup Table View / Collection View section

### ISSUE THREAD

**Issue by serhii-londar** [vsouza/awesome-ios#2507]
As there are a lot of projects in [Table View / Collection View](https://github.com/vsouza/awesome-ios#table-view--collection-view) section there is an idea to separate this section. I think we can create subcategories with projects for UITableView and UICollectionView and projects which are for booth of them. Also, we can create a subsection for cells. What do you think @vsouza @dkhamsing @lfarah @arasu01?

**Comment by vsouza** [comment]
@serhii-londar I moved some projects to a new category called `Cards`.

**Comment by vsouza** [comment]
I'm thinking to create a sub-category to deal with placeholders too.

**Comment by lfarah** [comment]
Totally agree. Any ideas on new subcategories? Let's open issues

**Comment by vsouza** [comment]
I created a new subcategory: Placeholders.

**Comment by vsouza** [comment]
I'll merge the @zhubofei pull request and close this issue. Great job guys ❤️

**Comment by lfarah** [comment]
Thanks!
