### ISSUE TITLE
SwiftyJot librarie to draw on UIImageView

### ISSUE THREAD

**Issue by gorbat-o** [vsouza/awesome-ios#2530]
Hey guys, 

What do you think about adding this library to the list ? =)
SwiftyJot - https://github.com/DavidLari/SwiftyJot

**Comment by vsouza** [comment]
@gorbat-o Please open a pull request with your contribution and make sure the project follows our [Contribution Guidelines](https://github.com/vsouza/awesome-ios/blob/master/.github/CONTRIBUTING.md)
