### ISSUE TITLE
Swippable Cell TableView subcategory

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#2535]
According to #2507, we should clean the TableView / Collectionview section. My next idea is to create a Swippable subcategory with the following libs:
* [MGSwipeTableCell](https://github.com/MortimerGoro/MGSwipeTableCell) - UITableViewCell subclass that allows to display swippable buttons with a variety of transitions.
* [BWSwipeRevealCell](https://github.com/bitwit/BWSwipeRevealCell) - A Swift library for swipeable table cells
* [MCSwipeTableViewCell](https://github.com/alikaragoz/MCSwipeTableViewCell) - :point_up_2: Convenient UITableViewCell subclass that implements a swippable content to trigger actions (similar to the Mailbox app).
* [SwipeCellKit](https://github.com/SwipeCellKit/SwipeCellKit) - Swipeable UITableViewCell based on the stock Mail.app, implemented in Swift.

**Comment by lfarah** [comment]
I didn't like ```Swippable Cell``` as a name. Any ideas?

**Comment by victorgama** [comment]
@lfarah Shouldn't it be Swipeable Cell? Or are you trying to get rid of the swipping altogether? :P

**Comment by lfarah** [comment]
I mean, I don't like the name. I think it needs to be more specific. Maybe I'm wrong and that's actually a good name, but I wanted to know from you guys

**Comment by victorgama** [comment]
Got it. IMHO that is a good name, since it is grouping swippeable cells 😛

**Comment by vsouza** [comment]
Guys can we close this thread?

**Comment by lfarah** [comment]
I'll open a PR!
