### ISSUE TITLE
Do you guys think that should be added?

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#260]
It is a cool concept, but not very well implemented yet. Is it worth to add In Awesome-iOS??
[CodeExample-AnnouncementSlider ](https://github.com/earthabbey/CodeExample-AnnouncementSlider/)

**Comment by vsouza** [comment]
if you have something awesome, even if it is only the concept. No problem.

**Comment by lfarah** [comment]
Not yet.
