### ISSUE TITLE
Animation Section

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#263]
I think that Animation is a big thing and should be separated from UI.
What do you guys think?

**Comment by dkhamsing** [comment]
How many projects would go in Animation ?

**Comment by miguelarauj1o** [comment]
we should create a new subsection inside UI section instead of separate them. 
See this repo: [awesome-ios-ui](https://github.com/cjwirth/awesome-ios-ui)

**Comment by vsouza** [comment]
We can create sub-categories of animation, what you think?

**Comment by vsouza** [comment]
Projects like this: https://github.com/facebook/pop

**Comment by lfarah** [comment]
Yeah!

**Comment by lfarah** [comment]
@miguelarauj1o how can we make this section as cool as awesome-ios-ui??

**Comment by lfarah** [comment]
Alright guys. Animation created. Let's bring all cool projects from Awesome-ios-ui and check if there's any animation stuff under ##UI
