### ISSUE TITLE
This list should be cleared of old libraries.

### ISSUE THREAD

**Issue by petrovi4** [vsouza/awesome-ios#2802]
Why are there so many garbage libraries? A huge number of links to repositories that have not been updated since 2015. Who can really use it?
On the one hand - the link is, it does not interfere with anyone. But try to find a really useful library if you have to go through all the garbage that has long been abandoned and can not be used.

**Comment by vsouza** [comment]
@petrovi4 Thanks for the feedback. 

I'm really planning a big clean for the next weeks. The list grew a lot in the last years and the iOS environment suffers with a lot of abandoned projects, so I'm finishing a tool to remove outdated projects.
