### ISSUE TITLE
Danger works incorrect

### ISSUE THREAD

**Issue by MaximKotliar** [vsouza/awesome-ios#2835]
Pull request, https://github.com/vsouza/awesome-ios/pull/2834 contains library name in title, but danger still warns

**Comment by vsouza** [comment]
@MaximKotliar Actually, Danger is correct, please check the makrdown preview of your change.

<img width="1519" alt="Screen Shot 2019-07-12 at 10 47 07" src="https://user-images.githubusercontent.com/484656/61132840-91cfb580-a492-11e9-8743-b6d553b3e6e8.png">

**Comment by MaximKotliar** [comment]
Oops, my fault. Thanks.
