### ISSUE TITLE
Add this example project with Siri and Shortcuts (Handoff) iOS 13

### ISSUE THREAD

**Issue by YanSteph** [vsouza/awesome-ios#2873]
This is an example project with Siri and Shortcuts (Handoff) iOS 13 whit presentation PDF 👍 
https://github.com/CoyoteLab/Studies-Siri-Shortcut-iOS-13

**Comment by lfarah** [comment]
Hey @YanSteph, this example project is really awesome! I was playing with shortcuts a couple months ago and this would have been really useful. Unfortunately we do not accept example projects.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
