### ISSUE TITLE
TKRubberIndicator - is categorized incorrectly

### ISSUE THREAD

**Issue by gmathi** [vsouza/awesome-ios#2901]
TKRubberIndicator - Rubber Indicator in Swift.
The above library is categorized as an **ActivityIndicator**. It is in fact a **PageControl**

**Comment by lfarah** [comment]
Hey @gmathi, thanks for contributing 🎉 
I just created a PR for this! Feel free to always open issues or open PRs whenever you see something wrong 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
