### ISSUE TITLE
support image for each repo will be more awesome

### ISSUE THREAD

**Issue by fewspider** [vsouza/awesome-ios#293]
thanks this repo,just a suggestion,support image for each repo will be more awesome

**Comment by lfarah** [comment]
Can you explain more about it? 
You want each of the libraries to have an image?

**Comment by fewspider** [comment]
@lfarah some ui repo,if has a image,can easy to find,not all repo must have an image

**Comment by lfarah** [comment]
We have waay to many UI Repo's. We can't afford to have images. It will be too heavy
