### ISSUE TITLE
PR ： The Travis CI build failed

### ISSUE THREAD

**Issue by yixiangboy** [vsouza/awesome-ios#2959]
PR ： The Travis CI build failed

**Comment by dkhamsing** [comment]
Thx, someone will take care of it!

**Comment by vsouza** [comment]
We're receiving a lot of HTTP 429 status in our CI. I'll investigate. Thanks.

**Comment by dkhamsing** [comment]
heya @vsouza I think 429 is from GitHub.. maybe expected since we are checking so many links.. an option would be to allow 429 errors. Let me know if you're interested.

on danger, looks like there's an issue with credentials
