### ISSUE TITLE
404 Errors

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#2994]
Found in #2993 

> [L0524] 404 https://github.com/BowdusBrown/Records  
[L2225] 404 https://github.com/BowdusBrown/Sheet  
[L2548] 404 https://github.com/BowdusBrown/Rotary

**Comment by pepiyox90** [comment]
> Found in #2993 
> 
> 
> 
> > [L0524] 404 https://github.com/BowdusBrown/Records  
> 
> [L2225] 404 https://github.com/BowdusBrown/Sheet  
> 
> [L2548] 404 https://github.com/BowdusBrown/Rotary  
> 
>
