### ISSUE TITLE
iOS 9 Sampler in Awesome-iOS?

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#301]
How can we add this to Awesome?
I really think that this page is cool, specially for 3D touch stuff
[iOS-9-Sampler](https://github.com/shu223/iOS-9-Sampler)

**Comment by vsouza** [comment]
this is a list of samples, right? `other awesome lists` maybe?

**Comment by dkhamsing** [comment]
it is a project that shows all new ios9 apis

**Comment by dkhamsing** [comment]
kinda tricky because that apps basically fits many categories: text, image, audio, ...
