### ISSUE TITLE
The Poly project is archived

### ISSUE THREAD

**Issue by MattHardcastle** [vsouza/awesome-ios#3019]
Google is shutting down the [Poly project](https://developers.google.com/poly/develop/) on June 30, 2021. @piemonte has archived the [unofficial Google Poly SDK](https://github.com/piemonte/Poly)

**Comment by piemonte** [comment]
thx @MattHardcastle ✌️

**Comment by vsouza** [comment]
Thanks for reporting @MattHardcastle
