### ISSUE TITLE
Domain for Awesome-ios is for Sale

### ISSUE THREAD

**Issue by WebSnke** [vsouza/awesome-ios#3111]
<p align="center">I just noticed that the website for this project can't be reached and that its domain is now for sale.</p>

![image](https://user-images.githubusercontent.com/94064167/210233381-3ae6de6c-ab75-474e-9598-bb3120633b84.png)

**Comment by WebSnke** [comment]
The description is probably supposed to link to https://awesome-ios.com.

**Comment by vsouza** [comment]
@WebSnke Thanks for reporting. This domain https://awesome-ios.com/ is from another project. I'll remove until this situation was solved.
