### ISSUE TITLE
Twin Prime

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#315]
[Twin Prime](http://www.twinprime.com) - Twin Prime makes mobile apps fast. Our technology works across the globe, on both WiFi and cellular networks.

**Comment by vsouza** [comment]
I think that fits in the Tools section, but I have my doubts

**Comment by dkhamsing** [comment]
Yea not sure

**Comment by dkhamsing** [comment]
Let's close this. Not sure it is that compelling.
