### ISSUE TITLE
Project admission

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#363]
Should we set a minimum number of stars for new GitHub projects added ? Like at least 10 or 20 or whatever 

cc @vsouza

**Comment by lfarah** [comment]
Hmmmm, I don't think so. It's all about quality in Awesome-iOS

**Comment by dkhamsing** [comment]
Ok how do you evaluate quality ?

**Comment by lfarah** [comment]
It's difficult, but by looking to the Readme, you can see what is good and what is garbage. Sometimes I also download and test if it's a plugin or UI

**Comment by miguelarauj1o** [comment]
I believe that good documentation is the key, not the number of stars or whatever.
Usually, good projects have good documentation.

**Comment by dkhamsing** [comment]
Thanks for your feedback

**Comment by lfarah** [comment]
totally agree!!!

**Comment by vsouza** [comment]
sorry for delay. I agree with @miguelarauj1o, good documentation is enough. Number of stars is very relative.
