### ISSUE TITLE
Server-side Swift

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#407]
What should we do with these new Swift Server Side Libraries?
[Perfect](https://github.com/PerfectlySoft/Perfect) - Server-side Swift. The Perfect library, application server, connectors and example apps. https://www.perfect.org

**Comment by vsouza** [comment]
they would be in the same category: https://github.com/glock45/swifter ?

**Comment by lfarah** [comment]
@vsouza Which is??

**Comment by dkhamsing** [comment]
How about a new section called `Server`
