### ISSUE TITLE
DarkLightning

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#413]
[DarkLightning](https://github.com/jensmeder/DarkLightning) -Simply the fastest way to transmit data between iOS and OSX

**Comment by dkhamsing** [comment]
Network?

**Comment by lfarah** [comment]
Isn't network more like Firebase, @dkhamsing ??

**Comment by dkhamsing** [comment]
Uh I meant Networking.. does that make sense. Like data transfer.. Firebase is a database

**Comment by lfarah** [comment]
@dkhamsing that's what happens when you're tired. I meant "Alamofire", not Firebase. Got the wrong "fire" library...

**Comment by dkhamsing** [comment]
I see

**Comment by dkhamsing** [comment]
Anyway I still think Networking 😊

**Comment by vsouza** [comment]
We can put in bridging section, shall we?

**Comment by dkhamsing** [comment]
@jensmeder can you think of a good category to place your library in https://github.com/vsouza/awesome-ios

**Comment by jensmeder** [comment]
Hmm what about creating a general category __Connectivity__? You could move the categories __Networking__, __Bluetooth__, and __Websocket__ as subcategories together with a new subcategory __USB__ or just __Miscellaneous__. Just a thought.

**Comment by dkhamsing** [comment]
@jensmeder thanks for the idea
