### ISSUE TITLE
SwiftFoundation

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#414]
[SwiftFoundation](https://github.com/PureSwift/SwiftFoundation) -Cross-Platform, Protocol-Oriented Programming base library to complement the Swift Standard Library. (Pure Swift, Supports Linux) :large_orange_diamond:[e]

**Comment by victorgama** [comment]
#Utility, again? hehe

**Comment by vsouza** [comment]
Bridging ?

**Comment by lfarah** [comment]
I don't see how this can be bridging, @vsouza

**Comment by vsouza** [comment]
cross-platform, I may have misinterpreted. Sorry heuheuhe

**Comment by lfarah** [comment]
@vsouza we don't have a cross-platform!

**Comment by lfarah** [comment]
@goktugyil

**Comment by goktugyil** [comment]
sdk
