### ISSUE TITLE
Podage

### ISSUE THREAD

**Issue by jensmeder** [vsouza/awesome-ios#438]
[Podage](https://www.github.com/jensmeder/Podage) - A simple tool to bundle any Cocoapod and its dependencies into frameworks - without using CocoaPods in your project setup.

**Comment by lfarah** [comment]
I think it should fall on #tools

**Comment by jensmeder** [comment]
What about "Dependency / Package Manager"? Functionality is comparable to Carthage using the centralized Cocoapods repo as foundation.

**Comment by lfarah** [comment]
hmm. Makes sense. Package Manager it is!
