### ISSUE TITLE
Appicontemplate 

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#445]
http://appicontemplate.com/ios8/ does not load, remove ?

**Comment by victorgama** [comment]
Ran into an issue with it and Travis yesterday. Requested it to rebuild, and then it passed, but I noticed other links also randomly fails.

Anyway, I'm :+1: for removal.

**Comment by dkhamsing** [comment]
Yup some links could be temporarily down or have an issue with Travis so it is good to verify the results

**Comment by dkhamsing** [comment]
Just a temporary issue https://travis-ci.org/vsouza/awesome-ios/builds/98056164

**Comment by dkhamsing** [comment]
Down again starting yesterday https://travis-ci.org/vsouza/awesome-ios/builds/98753652
