### ISSUE TITLE
Category ordering

### ISSUE THREAD

**Issue by victorgama** [vsouza/awesome-ios#450]
Hey guys!

I'm not sure if what I'm doing is right, so I decided to ask: You may have noticed I keep asking people to add (or move) new projects to the bottom, to keep categories in chronological order rather than alphabetical. Shall we keep categories in chronological, alphabetical or any ordering? (When, by the last, I mean, just accept the PR independently where the OP placed the new item)

Thanks!

cc/ @vsouza @dkhamsing @lfarah

**Comment by dkhamsing** [comment]
Suggestion should be added last at bottom https://github.com/vsouza/awesome-ios/blob/master/CONTRIBUTING.md

**Comment by victorgama** [comment]
Thank you, @dkhamsing. I just needed to confirm this is still being used.
