### ISSUE TITLE
Create Menu section under UI

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#460]
Move the following there

1. ENSwiftSideMenu 
- RESideMenu 
- PagingMenuController 
- RadialMenu  
- VLDContextSheet 
- cariocamenu
- GuillotineMenu  
- MediumMenu 
- SwiftySideMenu
- LLSlideMenu  
- Swift-Slide-Menu  
- SSASideMenu

**Comment by lfarah** [comment]
Thanks, @dkhamsing . That was a big one!
