### ISSUE TITLE
Regex

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#478]
[Regex](https://github.com/sharplet/Regex) - A Swift µframework providing an NSRegularExpression-backed Regex type :large_orange_diamond:

**Comment by victorgama** [comment]
#Utility, maybe?

**Comment by vsouza** [comment]
we have only this regex project in awesome?

**Comment by dkhamsing** [comment]
yup

**Comment by vsouza** [comment]
i think regex is an extensive field to explore, we can collect some projects and organize a new category. What you think guys?

ex: https://github.com/kasei/SwiftRegex

**Comment by dkhamsing** [comment]
agreed

**Comment by victorgama** [comment]
Sounds good! (:

**Comment by vsouza** [comment]
@lfarah ?

**Comment by lfarah** [comment]
@vsouza Let's find at least 3 items and then we can do a Category. What do you think?

**Comment by dkhamsing** [comment]
https://github.com/cezheng/PySwiftyRegex

**Comment by lfarah** [comment]
Thanks guys, this group is awesome!
