### ISSUE TITLE
Every.swift

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#501]
[Every.swift](https://github.com/samhann/Every.swift) - A swift wrapper for NSTimer :large_orange_diamond:

**Comment by vsouza** [comment]
__DateTools__ are in Utility, another subcategory maybe? with date and time related projects?

**Comment by vsouza** [comment]
@lfarah ?

**Comment by vsouza** [comment]
@dkhamsing ?

**Comment by dkhamsing** [comment]
Yea lets create Date & Time or something similar
