### ISSUE TITLE
Graphicz

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#507]
[Graphicz](https://github.com/SwiftKitz/Graphicz) - Light-weight, operator-overloading-free complements to CoreGraphics! :large_orange_diamond:

**Comment by vsouza-luizalabs** [comment]
nice project! 

i think we need a new category __CoreGraphics__ what u think?

some other projects:

https://github.com/mysterioustrousers/MTGeometry
https://github.com/mpw/MPWDrawingContext
https://github.com/pkluz/PKCoreTechniques

**Comment by vsouza** [comment]
i think we need a new category __CoreGraphics__ what u think?

some other projects:
https://github.com/pkluz/PKCoreTechniques
https://github.com/mpw/MPWDrawingContext
