### ISSUE TITLE
Swift Extensions section

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#517]
I discussed with @vsouza and we saw that the best way to organize them is to put only a single section since users download the extensions before they have a problem while programming, and not after, like almost all the libraries at Awesome-iOS.
What do you guys think?

Apps that would fall there:
* ~~[Sugar](https://github.com/hyperoslo/Sugar) - Sugar is a sweetener for your Cocoa implementations. :large_orange_diamond:~~ added in pr #522
* [SwiftFoundation](https://github.com/PureSwift/SwiftFoundation) -Cross-Platform, Protocol-Oriented Programming base library to complement the Swift Standard Library. (Pure Swift, Supports Linux) :large_orange_diamond:
* [EZSwiftExtensions](https://github.com/goktugyil/EZSwiftExtensions) - :smirk: How Swift standard types and classes were supposed to work. :large_orange_diamond:
* [DynamicColor](https://github.com/yannickl/DynamicColor) - Yet another extension to manipulate colors easily in Swift. :large_orange_diamond:
* [SwiftHEXColors](https://github.com/thii/SwiftHEXColors) - HEX color handling as an extension for UIColor. :large_orange_diamond:
* [Timepiece](https://github.com/naoty/Timepiece) - Intuitive NSDate extensions :large_orange_diamond:
* [Oriole](https://github.com/tptee/Oriole) - A functional utility belt implemented as Swift 2.0 protocol extensions. :large_orange_diamond:
* [OptionalExtensions](https://github.com/RuiAAPeres/OptionalExtensions) - Swift µframework with extensions for the Optional Type. :large_orange_diamond:
* [Pluralize.swift](https://github.com/joshualat/Pluralize.swift) - Great Swift String Pluralize Extension :large_orange_diamond:
* [Then](https://github.com/devxoul/Then) - ✨ Super sweet syntactic sugar for Swift initializers. :large_orange_diamond:

**Comment by lfarah** [comment]
@dkhamsing

**Comment by dkhamsing** [comment]
Hm shouldn't the color ones go under Color

**Comment by lfarah** [comment]
@dkhamsing if we do that, it woudn't be consistent... Can we put in both color and Extensions?
I see myself using this category by every project, I open the Extensions section and I use about 5 of them. If the extensions are separated, it's not easy to search, since Extensions are kinda Xcode Plugins, so it should have a Category for itself.

**Comment by dkhamsing** [comment]
Hm if you both agree, go for it 🤔

**Comment by lfarah** [comment]
@dkhamsing me and @vsouza found a better option: instead of a section, now Extensions have a tag, which is 🔶[e]. What do you think?

**Comment by dkhamsing** [comment]
uhh how about `🔶e` or `🔶ext`, the formatting makes it stand out more

**Comment by vsouza** [comment]
i think [e] is more easy to find in browser search, or we can think something like this.

**Comment by dkhamsing** [comment]
How about `🔶[e]`?

**Comment by vsouza** [comment]
it seems that you agree on :small_orange_diamond: [e] and that's ok for me too.
