### ISSUE TITLE
ReduxKit

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#518]
[ReduxKit](https://github.com/ReduxKit/ReduxKit) - Redux for Swift - a predictable state container for Swift apps http://reduxkit.github.io/ReduxKit/ :large_orange_diamond:

**Comment by lfarah** [comment]
@vsouza just like #499

**Comment by agentk** [comment]
Also note ReduxKit and Swift-Flow have merged into ReSwift. Referenced in #542

**Comment by lfarah** [comment]
Thanks, @agentk
