### ISSUE TITLE
Create Label section under UI

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#524]
There are a lot of label libraries under UI. It's time for a new section!
 * [LTMorphingLabel](https://github.com/lexrus/LTMorphingLabel) - Graceful morphing effects for UILabel written in Swift. :large_orange_diamond:
 * [ActiveLabel.swift](https://github.com/optonaut/ActiveLabel.swift) - UILabel drop-in replacement supporting Hashtags (#), Mentions (@) and URLs (http://) :large_orange_diamond:
 * [MZTimerLabel](https://github.com/mineschan/MZTimerLabel) - A handy class for iOS to use UILabel as a countdown timer or stopwatch just like in Apple Clock App.

**Comment by dkhamsing** [comment]
:+1:

**Comment by lfarah** [comment]
Thanks, @dkhamsing
