### ISSUE TITLE
CKWaveCollectionViewTransition

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#526]
[CKWaveCollectionViewTransition](https://github.com/CezaryKopacz/CKWaveCollectionViewTransition) - Cool wave like transition between two or more UICollectionView :large_orange_diamond:

Is this #Animation or #UI?

**Comment by dkhamsing** [comment]
I'd go with Animation

**Comment by lfarah** [comment]
Thanksm @dkhamsing !

**Comment by dkhamsing** [comment]
:smile:
