### ISSUE TITLE
Result

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#540]
[Result](https://github.com/antitypical/Result) - Swift type modelling the success/failure of arbitrary operations. :large_orange_diamond:

**Comment by lfarah** [comment]
@antitypical do you know on what category we could add *Result*?

**Comment by lfarah** [comment]
@mdiep do you know on what category we could add Result?

**Comment by mdiep** [comment]
I dunno, _Data Structures / Algorithms_?
