### ISSUE TITLE
SwiftyGPIO

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#545]
[SwiftyGPIO](https://github.com/uraimo/SwiftyGPIO) -  A Swift library to interact with Linux GPIO/SPI on ARM (RaspberryPi, BeagleBone, CHIP, etc...) :large_orange_diamond:

**Comment by lfarah** [comment]
@uraimo, do you know on what category we could add *SwiftyGPIO*?

**Comment by uraimo** [comment]
Hi, thanks for considering SwiftyGPIO, i'd recommend something like "Internet of Things" or "Embedded Systems" since that's where the library should end up.

**Comment by miguelarauj1o** [comment]
@lfarah, can we close this issue?
I think that "Embedded Systems" pretty good.

**Comment by uraimo** [comment]
It's ok for me too  👍

**Comment by dkhamsing** [comment]
Sounds good, lets add to Embedded Systems and close :)

**Comment by miguelarauj1o** [comment]
great!

**Comment by sushihangover** [comment]
Just a question: . This is a library written in the Swift language and does not run on iOS/macOS, but runs on embedded Linux/IoT-based hardware...

So are there are non-iOS/macOS libraries include in `Awesome iOS`?

**Comment by dkhamsing** [comment]
Good point

Closing
