### ISSUE TITLE
Tag Carthage-compatible projects

### ISSUE THREAD

**Issue by victorgama** [vsouza/awesome-ios#552]
Hey guys, is it interesting to tag projects supporting [Carthage](https://github.com/Carthage/Carthage)? Maybe using :black_circle:

I'm moving away from CocoaPods, so the tag would help when searching the list.

What you think?

**Comment by lfarah** [comment]
How do we deal with projects that are already Swift :large_orange_diamond:? We should do :large_orange_diamond::black_circle:?
And then there are the Swift extensions, so :large_orange_diamond:[e]:black_circle:
We need to think about this.

**Comment by lfarah** [comment]
And @victorgama, are you willing not to use a library just because it doesn't support  Carthage?

**Comment by victorgama** [comment]
@lfarah Yeah, that would look a little messy, but it just an idea, anyway.

Answering your question: No, I wouldn't. But in those cases, I import the sources and compile it on my own, which is not a big problem when dealing with, say, 97% of the libs I use; but I confess that some of them can still be a PITA (AFNetworking, I'm looking at you) :stuck_out_tongue:

**Comment by dkhamsing** [comment]
You could use this symbol ◉

:smile:

**Comment by olivierlesnicki** [comment]
How would you tag Carthage itself?

**Comment by vsouza** [comment]
I disagree, I think we can greatly enhance the work of updating the list.
