### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#568]
@vsouza said we needed a new logo, so me and some Friends are playing with Sketch and coming up with some ideas:
![awesomeioslogo](https://cloud.githubusercontent.com/assets/6511079/12835293/c16cfcfa-cb63-11e5-9014-4fde23fe8c50.png)
![awesomeiosv2](https://cloud.githubusercontent.com/assets/6511079/12835770/deca39bc-cb67-11e5-8586-f8c98c062ae8.png)
![awesome ios final](https://cloud.githubusercontent.com/assets/6511079/12835778/fba6b4ca-cb67-11e5-9e34-5e51fe443a4a.png)
![awesomeios3](https://cloud.githubusercontent.com/assets/6511079/12837998/0f359168-cb7d-11e5-93a6-5de346845650.png)

**Comment by dkhamsing** [comment]
nice

**Comment by vineethvijayan** [comment]
+1

**Comment by victorgama** [comment]
+1 for the second one! 👌🏻
