### ISSUE TITLE
Kill Providers section

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#569]
Providers section isn't organized, doesn't have project descriptions and I don't think we need this section since each project could fit somewhere else, like Urban Airship: push notifications

**Comment by dkhamsing** [comment]
Uh I put that in, and the idea is that those are Push Notifications Providers.. maybe it is not clear because it is not in the table of contents

Let me update that

**Comment by dkhamsing** [comment]
@lfarah can you see if https://github.com/vsouza/awesome-ios/pull/572 improves this, and merge if you agree

Thanks
