### ISSUE TITLE
Swiftline

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#570]
[Swiftline](https://github.com/Swiftline/Swiftline) - Swiftline is a set of tools to help you create command line applications. :large_orange_diamond:

**Comment by vsouza** [comment]
at this moment i think will be more appropriate create a new category with name "command line", i believe that we will receive a lot of pull request with projects like this in near future.

We can add this project too: https://github.com/jatoben/CommandLine

**Comment by dkhamsing** [comment]
Nice
