### ISSUE TITLE
Delete projects that don't conform to the Awesome rules

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#574]
Let's clean up old projects at some point

First discussed in #562
> In about an year, we should do this cleaning

**Comment by vsouza** [comment]
we need to create some rules for this. 

My 2 cents:

 * Projects doesn't have commit for more than two years.
 * Projects doesn't support ios 7 and later.
 * Projects with README in another language (Chinese, Japanese, Portuguese and etc)
 * Projects that we can not clearly understand the objective.

What do you think guys?

@lfarah @dkhamsing @victorgama @CavalcanteLeo

**Comment by olivierlesnicki** [comment]
@vsouza not sure about the "another language" one... but I think the other rules make a lot of sense.

**Comment by vsouza** [comment]
@olivierlesnicki documentation is essential part of a project, the README does not need to be completely in English, but I believe that a simple explanation in a "universal" language would be valid.

**Comment by olivierlesnicki** [comment]
@vsouza Google Translate does a pretty decent job, and the best ever react-native tutorials I've stumbled upon were in Japanese!

**Comment by vsouza** [comment]
I get it. I think we can keep it that way for now. :smile:

**Comment by lfarah** [comment]
I personally hate documentations that aren't in English. I'm not a native English speaker, but people need to understand that opensource projects **need** to be in English. It's some sort of _respect_ to the other devs.

**Comment by lfarah** [comment]
I think we actually need to test if the project works. But this will take _a lot of_ time

**Comment by vsouza** [comment]
@dkhamsing @lfarah @olivierlesnicki @victorgama we can start with this rules?

**Comment by dkhamsing** [comment]
@lfarah had suggested we do it in one year, it has been one month

but yeah if you find outdated projects, we can delete em

**Comment by dkhamsing** [comment]
Here are some info.. based on last commit

⭐️  582 https://github.com/steipete/SDURLCache  last commit 35 months ago
⭐️  108 https://github.com/vinhnx/ColorArt  last commit 27 months ago
⭐️  326 https://github.com/chasseurmic/TWRCharts  last commit 20 months ago
⭐️  276 https://github.com/apparentsoft/ReactiveCoreData  last commit 18 months ago
⭐️  191 https://github.com/OliverLetterer/SLRESTfulCoreData  last commit 19 months ago
⭐️  104 https://github.com/lauraskelton/simple-share  last commit 24 months ago
⭐️  338 https://github.com/ohwutup/OWUProximityManager  last commit 27 months ago
⭐️  746 https://github.com/lgaches/BeaconEmitter  last commit 20 months ago
⭐️  266 https://github.com/conradev/BlockTypeDescription  last commit 36 months ago
⭐️  1236 https://github.com/route-me/route-me  last commit 41 months ago
⭐️  358 https://github.com/gdawg/uiimage-dsp  last commit 37 months ago
⭐️  36 https://github.com/cdzombak/CDZPinger  last commit 21 months ago
⭐️  536 https://github.com/dingbat/nsrails  last commit 18 months ago
⭐️  217 https://github.com/Cue/ocstyle  last commit 32 months ago
⭐️  82 https://github.com/mindsnacks/MSActiveConfig  last commit 29 months ago
⭐️  635 https://github.com/mattt/SkyLab  last commit 18 months ago
⭐️  165 https://github.com/zucchini-src/zucchini  last commit 21 months ago

**Comment by vsouza** [comment]
wow :clap:

**Comment by dkhamsing** [comment]
:sweat_smile:

**Comment by victorgama** [comment]
@vsouza Sounds good! (But I agree on rejecting projects in another language...)

**Comment by lfarah** [comment]
Awesome work, guys!
We should create a README talking about the rules of an Awesome App. What do you guys think?

- Projects doesn't have commit for more than two years.
- Projects doesn't support ios 7 and later.
- Projects with README in another language (Chinese, Japanese, Portuguese and etc)
- Projects that we can not clearly understand the objective.
- Projects without clear README

**Comment by lfarah** [comment]
Can we close this issue and if we find those projects, we take them off mentioning what rule made them ineligible?

**Comment by vsouza** [comment]
Yep. Thank you guys. ❤️
Em Mon, Mar 21, 2016 às 11:46 PM, Lucas Farah <notifications@github.com>
escreveu:
