### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#579]
[Colors](https://github.com/icodeforlove/Colors) - A pure Swift library for using ANSI codes. Basically makes command-line coloring and styling very easy! :large_orange_diamond:[e]

Is this under /Colors, or under /Text? This lib is different than all the color frameworks because it focuses on extending String class

**Comment by lfarah** [comment]
@vsouza

**Comment by vsouza** [comment]
this project is under `Logging` category, https://github.com/onevcat/Rainbow

They are very similar projects. We can put in logging category.
