### ISSUE TITLE
CSwiftV

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#585]
[CSwiftV](https://github.com/Daniel1of1/CSwiftV) - A csv parser written in swift conforming to rfc4180 :large_orange_diamond:

**Comment by lfarah** [comment]
@vsouza

**Comment by vsouza** [comment]
wow! <3

**Comment by vsouza** [comment]
we can change `XML / HTML` subcategory to `XML / HTML / CSV` and maybe add this lib too:

https://github.com/naoty/SwiftCSV

**Comment by lfarah** [comment]
I don't see any better place to put, so let's do it
