### ISSUE TITLE
PASImageView

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#592]
[PASImageView](https://github.com/abiaad/PASImageView) - Rounded async imageview downloader lightly cached and written in Swift :large_orange_diamond:

Same problem as #586: Is this under Is this under /Image or under /Activity Indicator?

**Comment by lfarah** [comment]
@victorgama what do you think?

**Comment by victorgama** [comment]
@lfarah Image suits it better. I'd say the activity indicator is just a side-effect. :P

**Comment by lfarah** [comment]
Thanks, @victorgama!
