### ISSUE TITLE
Surge

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#594]
[Surge](https://github.com/mattt/Surge) - A Swift library that uses the Accelerate framework to provide high-performance functions for matrix math, digital signal processing, and image manipulation. :large_orange_diamond:

:large_orange_diamond: This is from an Apple employee!!!! :large_orange_diamond:

**Comment by victorgama** [comment]
LOL didn't know Apple hired Mattt :scream:

**Comment by dkhamsing** [comment]
Well.. he created it before he joined Apple

**Comment by dkhamsing** [comment]
@victorgama https://github.com/apple/swift-package-manager/graphs/contributors

**Comment by vsouza** [comment]
wow!

**Comment by victorgama** [comment]
LOL

**Comment by vsouza** [comment]
@lfarah we can close this issue?

**Comment by lfarah** [comment]
@vsouza Good job on catching that! Yes, sure!
