### ISSUE TITLE
SwiftKVC

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#595]
[SwiftKVC](https://github.com/bradhilton/SwiftKVC) - Key-Value Coding (KVC) for native Swift classes and structs :large_orange_diamond:

**Comment by lfarah** [comment]
@bradhilton do you know on what category we could add *SwiftKVC*?

**Comment by bradhilton** [comment]
I'd add it to *Reflection*

**Comment by lfarah** [comment]
@bradhilton thanks 😄
