### ISSUE TITLE
Switchboard

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#596]
[Switchboard](https://github.com/KeepSafe/Switchboard) - Switchboard - easy and super light weight A/B testing for your mobile iPhone or android app. This mobile A/B testing framework allows you with minimal servers to run large amounts of mobile users.

**Comment by vsouza** [comment]
More A/B testing projects:

https://github.com/mattt/SkyLab
https://github.com/mindsnacks/MSActiveConfig

We can change title of subcategory "TDD / BDD" to "TDD / BDD / A/B" and add these projects. What u think?

**Comment by lfarah** [comment]
Thanks, @vsouza !
