### ISSUE TITLE
Localization Category

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#619]
* [Hodor](https://github.com/Aufree/Hodor) - Simple solution to localize your iOS App.
 * [Swifternalization](https://github.com/tomkowz/Swifternalization) - Localize iOS apps in a smarter way using JSON files. Swift framework. :large_orange_diamond:
 * [Rubustrings](https://github.com/dcordero/Rubustrings) - Check the format and consistency of Localizable.strings files
 * [BartyCrouch](https://github.com/Flinesoft/BartyCrouch) - Incrementally update your Storyboard localizations with ease. :large_orange_diamond:
 * [Lin](https://github.com/questbeat/Lin) - Xcode plugin that provides auto-completion for NSLocalizedString.
 * [Localize-Swift](https://github.com/marmelroy/Localize-Swift) - Swift 2.0 friendly localization and i18n with in-app language switching :large_orange_diamond:

**Comment by lfarah** [comment]
@vsouza @dkhamsing any thoughts on this?

**Comment by dkhamsing** [comment]
Sounds good

**Comment by lfarah** [comment]
@dkhamsing thanks!

**Comment by vsouza** [comment]
:clap:
