### ISSUE TITLE
Spots

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#620]
[Spots](https://github.com/hyperoslo/Spots) - Spots is a view controller framework that makes your setup and future development blazingly fast. :large_orange_diamond:

**Comment by zenangst** [comment]
I guess this would fit in under `UI` seeing as it creates collections and/or views in sequence for you.
What do you think @lfarah ?

**Comment by lfarah** [comment]
Yeah, makes total sense, @zenangst. Thanks for contributing! 😀
