### ISSUE TITLE
Comand Line Category

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#621]
[Swiftline](https://github.com/Swiftline/Swiftline) - Swiftline is a set of tools to help you create command line applications. :large_orange_diamond:
[CommandLine](https://github.com/jatoben/CommandLine) - A pure Swift library for creating command-line interfaces :large_orange_diamond:
[Colors](https://github.com/paulot/Colors) - Terminal Colors for Swift :large_orange_diamond:
[Commander](https://github.com/kylef/Commander) - Compose beautiful command line interfaces in Swift :large_orange_diamond:

**Comment by lfarah** [comment]
#570

**Comment by lfarah** [comment]
Updated with Commander, created in issue #593

**Comment by vsouza** [comment]
i'll close, ok?

**Comment by lfarah** [comment]
@vsouza why did you close it?

**Comment by vsouza** [comment]
I understood that was moved to another issue

**Comment by vsouza** [comment]
sorry :cry:

**Comment by lfarah** [comment]
@vsouza no problem! Now it's done. :smile:

**Comment by vsouza** [comment]
heuehueheueh :+1:
