### ISSUE TITLE
Swicon

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#624]
[Swicon](https://github.com/UglyTroLL/Swicon) - Use 1600+ icons (and more!) from FontAwesome and Google Material Icons in your swift/iOS project in an easy and space-efficient way! :large_orange_diamond:

**Comment by lfarah** [comment]
@UglyTroLL do you know on what category we could add *Swicon*?

**Comment by lfarah** [comment]
Closed due inactivity

**Comment by UglyTroLL** [comment]
Shit, sorry I didn't see the first message you sent last year :(
It should be under 'Text/Font' if it's still OK to put it in
