### ISSUE TITLE
Authentication Category 

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#639]
[Heimdallr.swift](https://github.com/rheinfabrik/Heimdallr.swift) - Easy to use OAuth 2 library for iOS, written in Swift. :large_orange_diamond:
[OhMyAuth](https://github.com/hyperoslo/OhMyAuth) - Simple OAuth2 library with a support of multiple services. :large_orange_diamond:
[OAuth2](https://github.com/p2/OAuth2) - OAuth2 framework for OS X and iOS, written in Swift. :large_orange_diamond:
[OAuthSwift](https://github.com/OAuthSwift/OAuthSwift) - Swift based OAuth library for iOS :large_orange_diamond:
[SimpleAuth](https://github.com/calebd/SimpleAuth) - Simple social authentication for iOS
[AuthenticationViewController](https://github.com/raulriera/AuthenticationViewController) - A simple to use, standard interface for authenticating to oauth 2.0 protected endpoints via SFSafariViewController. :large_orange_diamond:

**Comment by dkhamsing** [comment]
Also https://github.com/calebd/SimpleAuth

**Comment by vsouza** [comment]
:clap: awesome projects.

**Comment by vsouza** [comment]
a new subcategory in `Security` section maybe?

**Comment by dkhamsing** [comment]
Could be it's own category
Btw, should be spelled `OAuth`

**Comment by vsouza** [comment]
but `OAuth` is not a security method?

**Comment by dkhamsing** [comment]
Good question. I think of Security for keeping data secure. OAuth is about authentication. What do you think?

**Comment by dkhamsing** [comment]
I'm editing original issue to add more libs

**Comment by vsouza** [comment]
in that case you are right. Authentication is more appropriate

**Comment by dkhamsing** [comment]
We could use `Authentication` to be more generic

**Comment by vsouza** [comment]
yep :+1:

**Comment by lfarah** [comment]
Authentication it is!

**Comment by lfarah** [comment]
Thanks guys!

**Comment by dkhamsing** [comment]
https://github.com/vsouza/awesome-ios/commit/b6a5aadefc8cb89ff738f71ac221203689fd4528
