### ISSUE TITLE
A/B Testing Section

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#652]
[Switchboard](https://github.com/KeepSafe/Switchboard) - Switchboard - easy and super light weight A/B testing for your mobile iPhone or android app. This mobile A/B testing framework allows you with minimal servers to run large amounts of mobile users.
[SkyLab](https://github.com/mattt/SkyLab) - Multivariate & A/B Testing for iOS and Mac
[MSActiveConfig](https://github.com/mindsnacks/MSActiveConfig) - Remote configuration and A/B Testing framework for iOS

**Comment by lfarah** [comment]
closes #596

**Comment by vsouza** [comment]
:clap:
