### ISSUE TITLE
QuickActions

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#653]
[QuickActions](https://github.com/ricardopereira/QuickActions) - Swift wrapper for iOS Home Screen Quick Actions (App Icon Shortcuts) :large_orange_diamond:

**Comment by lfarah** [comment]
@ricardopereira, on what section can we add your lib?

**Comment by ricardopereira** [comment]
Great question 😅
Maybe _UI_.

**Comment by lfarah** [comment]
@ricardopereira the problem is that Quick Actions are kinda outside the app, so I really have no idea where to put this 😢

**Comment by ricardopereira** [comment]
Hardware/Force Touch category?

**Comment by lfarah** [comment]
Good idea!

**Comment by lfarah** [comment]
Thanks, @ricardopereira 😄
