### ISSUE TITLE
Nomoji :cry:

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#66]
Hey buddy, doesn't look like :large_orange_diamond: is working in the readme.. is there some workaround?

**Comment by muescha** [comment]
fun fact in [CONTRIBUTING.md](https://github.com/vsouza/awesome-ios/blob/master/CONTRIBUTING.md) the sign works

**Comment by dkhamsing** [comment]
Maybe we can ask @github

**Comment by vsouza** [comment]
@github :cry:

**Comment by vsouza** [comment]
https://twitter.com/__vsouza/status/573838868757221376

**Comment by vsouza** [comment]
I've received an email from James Dennes (GitHub Staff) 

```
We have temporarily disabled Emoji rendering in overly large documents because of performance issues. This is a temporary measure while we work on improving the performance of our rendering pipeline. We will restore this functionality as soon as possible. Aoplogies for the inconvenience.

Thanks,
James

```

**Comment by dkhamsing** [comment]
Ah.. too bad :disappointed:
