### ISSUE TITLE
Validated

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#662]
[Validated](https://github.com/Ben-G/Validated) - A Swift μ-Library for Somewhat Dependent Types :large_orange_diamond:

**Comment by lfarah** [comment]
@Ben-G do you know on what section we could add *Validated*?

**Comment by Ben-G** [comment]
@lfarah Given the existing sections, most likely in `Libraries/Utility`.

**Comment by lfarah** [comment]
Ok, will add it on *Utility*

Thanks for helping! 😄
