### ISSUE TITLE
Swift 360 Video Player

### ISSUE THREAD

**Issue by Aralekk** [vsouza/awesome-ios#664]
[simple360player](https://github.com/Aralekk/simple360player_iOS) - Free & ad-free 360 VR Video Player. Flat or Stereoscopic. In Swift 2.

**Comment by lfarah** [comment]
@Aralekk this goes to [Video Section](https://github.com/vsouza/awesome-ios#video).

Do you wanna do the PR, or I can do it for you?

**Comment by Aralekk** [comment]
@lfarah Yes sure, do it :)
