### ISSUE TITLE
VR Toolkit in SceneKit and Swift 2

### ISSUE THREAD

**Issue by Aralekk** [vsouza/awesome-ios#666]
For a VR or SceneKit section:
[VR_Toolkit_iOS](https://github.com/Aralekk/VR_Toolkit_iOS) SceneKit based toolkit to create interactive VR scenes, games or else. In Swift 2.

**Comment by lfarah** [comment]
@Aralekk I'm closing this issue because I created [an issue about a category for VR](https://github.com/vsouza/awesome-ios/issues/707)
