### ISSUE TITLE
Guise

### ISSUE THREAD

**Issue by Revolucent** [vsouza/awesome-ios#679]
[Guise](https://github.com/prosumma/Guise) - An elegant, flexible, type-safe dependency resolution framework for Swift :large_orange_diamond:

**Comment by lfarah** [comment]
@Prosumma, do you know on what category we could add *Guise*?

**Comment by Revolucent** [comment]
I really don't. Otherwise I would have added it myself with a PR.

**Comment by lfarah** [comment]
@Revolucent, oh, I didn't know that you were @Prosuma.... I'm working in getting *Guise* a place!
