### ISSUE TITLE
Add MailCore2

### ISSUE THREAD

**Issue by catalandres** [vsouza/awesome-ios#697]
https://github.com/MailCore/mailcore2

**Comment by dinhviethoa** [comment]
Probably networking.

**Comment by lfarah** [comment]
Hmmm, that's a hard one.
@dkhamsing don't you think that this is too specific to be under ```Networking```?
99% of the Networking libraries involve more of a normal network request, and ```MailCore2``` is only about emails

**Comment by lfarah** [comment]
@vsouza what do you think about that?

**Comment by dkhamsing** [comment]
How about an email subsection under networking
