### ISSUE TITLE
Swift Implementation of UIView_2_PDF

### ISSUE THREAD

**Issue by kayoslab** [vsouza/awesome-ios#701]
I made a Swift Implementation with an example Project of [UIView_2_PDF](https://github.com/RobertAPhillips/UIView_2_PDF). You can get the Project [here](https://github.com/kayoslab/SwiftPDFGenerator).

**Comment by lfarah** [comment]
Hey @kayoslab, I really liked your Swift port. I'd love to contribute to you library!
What do you think about making ```SwiftPDFGenerator``` it's own library and use your project as an example?
I'm happy to help you get started so we can add it to Awesome iOS as quick as possible! :smile:

**Comment by kayoslab** [comment]
Hey @lfarah I already thought about making it a library. At the moment I'm constantly adding features to the Class, because I needed it in a running project. If you want to, you can contribute to the project. If you are seriously interested, I could add you to the collaborators list.

**Comment by kayoslab** [comment]
Hey @lfarah I already thought about making it a library. At the moment I'm constantly adding features to the Class, because I needed it in a running project. If you want to, you can contribute to the project.

**Comment by lfarah** [comment]
@kayoslab I'm closing this issue right now, but I'll be contributing to SwiftPDFGenerator in the next days!
