### ISSUE TITLE
Rating Stars Section

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#723]
* [FloatRatingView](https://github.com/glenyi/FloatRatingView) - Whole, half or floating point ratings control written in Swift :large_orange_diamond:
 * [TTGEmojiRate](https://github.com/zekunyan/TTGEmojiRate) - An emoji-liked rating view for iOS, implemented in Swift. :large_orange_diamond:
 * [StarryStars](https://github.com/peterprokop/StarryStars) - iOS GUI library for displaying and editing ratings
 * [Cosmos](https://github.com/marketplacer/Cosmos) - A star rating control for iOS / Swift :large_orange_diamond:

**Comment by lfarah** [comment]
@dkhamsing I'm really not sure what to do on this one. It's big enough to have a section, but not important enough to deserve a section

**Comment by dkhamsing** [comment]
Hmm.. I say create it

**Comment by lfarah** [comment]
Alright. doing it right now. Thanks! 😄

**Comment by vsouza** [comment]
it just an another subcategory of ui, non?

**Comment by lfarah** [comment]
@vsouza added /UI/Rating Stars
