### ISSUE TITLE
Underscore.m

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#75]
https://github.com/robb/Underscore.m by @robb looks really cool, not sure where it fits..

**Comment by lfarah** [comment]
I think that this would go to [Xcode -> Plugins](https://github.com/vsouza/awesome-ios#plugins).
What do you think?

**Comment by dkhamsing** [comment]
It's not a plugin, I guess the question is where should it go

**Comment by vsouza** [comment]
we can create a new category for matrix manipulation and dictionary. What do you think?

**Comment by dkhamsing** [comment]
👍

**Comment by dkhamsing** [comment]
A couple of new category name ideas:
- Data
- Utility

What do you think?

**Comment by vsouza** [comment]
@dkhamsing  i'll close this issue. i'll be waiting you fix conflicts in your commit. Thanks.
