### ISSUE TITLE
Sort UI section

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#750]
Alphabetical order? @lfarah 

Current order:
```
Activity Indicator
Alert View
Calendar
Form
Table View
TextField & TextView
Keyboard
Button
Menu
Modal Transition
Label
Popup
Pull to Refresh
Rating Stars
Slider
Stepper
Tab Bar
Tag
```

Sorted:
```
Activity Indicator
Alert View
Button
Calendar
Form
Keyboard
Label
Menu
Modal Transition
Popup
Pull to Refresh
Rating Stars
Slider
Stepper
Tab Bar
Table View
Tag
TextField & TextView
```

**Comment by lfarah** [comment]
Every time I add a new section I try do do in Alphabetical order and it makes total sense.
Go ahead 😉

**Comment by lfarah** [comment]
Also, can we make the entire Awesome-iOS in Alphabetical order, @vsouza?

**Comment by vsouza** [comment]
I was thinking about this a few weeks ago.  Make sense, with a lot of projects, is a way to organize all things. @dkhamsing awesome-bot supports alphabetical order validation?

**Comment by dkhamsing** [comment]
@vsouza nope

**Comment by lfarah** [comment]
@dkhamsing do you wanna do the UI or you want me to do it?

**Comment by dkhamsing** [comment]
@lfarah can u take care of it?

**Comment by lfarah** [comment]
for sure!

**Comment by lfarah** [comment]
Done!
