### ISSUE TITLE
Beta Distribution category

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#753]
I don't think that [Beta Distribution](https://github.com/vsouza/awesome-ios#beta-distribution) category should be inside [Testing](https://github.com/vsouza/awesome-ios#testing) category

**Comment by lfarah** [comment]
@dkhamsing @vsouza what do you guys think?

**Comment by dkhamsing** [comment]
Looks like it is

- [Testing](#testing)
    - [TDD / BDD](#tdd--bdd)
    - [A/B Testing](#ab-testing)
    - [UI Testing](#ui-testing)
    - [Beta Distribution](#beta-distribution)

**Comment by vsouza** [comment]
We should rename `Deployment` category to `Deployment / Distribution` and merge these categories.

**Comment by lfarah** [comment]
I agree with @vsouza
