### ISSUE TITLE
Local URL Image Library

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#763]
@osrl on Gitter:
> Hello everyone. Is there an image library that supports loading local images (which is downloaded on disk)? Something like ImageLoader(NSURL(string: "file://....")) . I've checked all Image Libraries, none of them mentions about local images. So I didn't try them before asking here.

**Comment by lfarah** [comment]
@dkhamsing do you know any lib for that?

**Comment by dkhamsing** [comment]
hey buddy nope :-(

**Comment by lfarah** [comment]
@goktugyil can we do an extension for that?

**Comment by goktugyil** [comment]
https://github.com/goktugyil/EZSwiftExtensions/blob/master/Sources/NSURLExtensions.swift
