### ISSUE TITLE
PagingView

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#781]
[PagingView](https://github.com/KyoheiG3/PagingView) - Infinite paging, Smart auto layout, Interface of similar to UIKit. :large_orange_diamond:

**Comment by lfarah** [comment]
@KyoheiG3 do you know on what category we could add *PagingView*?

**Comment by KyoheiG3** [comment]
@lfarah I think `Table View` may be. however I want to add `Collection View`.
thanks.

**Comment by lfarah** [comment]
@dkhamsing @vsouza should we add a ```Collection View``` section?

**Comment by vsouza** [comment]
I think more appropriate 😄

**Comment by lfarah** [comment]
I'm closing this issue so we can discuss the rest on #898
