### ISSUE TITLE
Reductio

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#784]
[Reductio](https://github.com/fdzsergio/Reductio) - Automatic summarizer text in Swift :large_orange_diamond:

**Comment by lfarah** [comment]
@dkhamsing @vsouza HOLY SHHHHHHH, THIS IS AMAZINGLY AMAZING!

**Comment by lfarah** [comment]
where would that fit? Text?

**Comment by dkhamsing** [comment]
ya

**Comment by lfarah** [comment]
I was thinking it could also fit ```Data structures/Algorithms section``` because it uses [TextRank](https://web.eecs.umich.edu/%7Emihalcea/papers/mihalcea.emnlp04.pdf), but you're right... It fits better under ```Text```

**Comment by dkhamsing** [comment]
this may seem radical.. but you could put it under both section (remember to white list it in .travis.yml)
