### ISSUE TITLE
DefaultStringConvertible

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#785]
[DefaultStringConvertible](https://github.com/jessesquires/DefaultStringConvertible) - A default CustomStringConvertible implementation for Swift types :large_orange_diamond:

**Comment by lfarah** [comment]
@jessesquires do you know on what category we could add *DefaultStringConvertible*?

**Comment by victorgama** [comment]
This is tricky and I believe we don't have a proper category for it. `Utility`, perhaps?

**Comment by jessesquires** [comment]
"Utility" would probably be best 👍

**Comment by victorgama** [comment]
Thank you, @jessesquires! Just added it.
