### ISSUE TITLE
StateView

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#786]
[StateView](https://github.com/sahandnayebaziz/StateView) - Views that automatically update themselves. :large_orange_diamond:

**Comment by lfarah** [comment]
@sahandnayebaziz do you know on what category we could add *StateView*?

**Comment by sahandnayebaziz** [comment]
@lfarah absolutely. UI or Reactive programming would make the most sense.

**Comment by lfarah** [comment]
*UI* it is! 👍 

Thanks for contributing! 😄
