### ISSUE TITLE
Math section

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#787]
[Euler](https://github.com/mattt/Euler) - Swift Custom Operators for Mathematical Notation :large_orange_diamond:
[SwiftMath](https://github.com/madbat/SwiftMath) - :triangular_ruler: A math framework for Swift. Includes: vectors, matrices, complex numbers, quaternions and polynomials. :large_orange_diamond:
[Arithmosophi](https://github.com/phimage/Arithmosophi) - A set of protocols for Arithmetic and Logical operations :large_orange_diamond:
[Surge](https://github.com/mattt/Surge) - A Swift library that uses the Accelerate framework to provide high-performance functions for matrix math, digital signal processing, and image manipulation. :large_orange_diamond:
[Upsurge](https://github.com/aleph7/Upsurge) - Swift + Accelerate :large_orange_diamond:
[Swift-MathEagle](https://github.com/rugheid/Swift-MathEagle) - A general math framework to make using math easy. Currently supports function solving and optimisation, matrix and vector algebra, complex numbers, big int and big frac and general handy extensions and functions. :large_orange_diamond:

**Comment by lfarah** [comment]
@dkhamsing @vsouza what do you guys think?

**Comment by dkhamsing** [comment]
would be great to have more libs in there but sure

**Comment by lfarah** [comment]
@dkhamsing found a couple more!

**Comment by vsouza** [comment]
It is a category with few projects in general, but still is a great idea to insert this new category.

**Comment by lfarah** [comment]
Alright. Adding it right now!

**Comment by vsouza** [comment]
some others projects

https://github.com/rugheid/Swift-MathEagle (in development)
https://github.com/noxytrux/SwiftGeom
https://github.com/nicklockwood/VectorMath

**Comment by lfarah** [comment]
@vsouza SwiftGeom hasn't been updated for the past 2 years

**Comment by lfarah** [comment]
@vsouza VectorMath won't compile on Swift's newest version

**Comment by vsouza** [comment]
=/
