### ISSUE TITLE
SwiftOCR

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#788]
[SwiftOCR](https://github.com/garnele007/SwiftOCR) - Fast and simple OCR library written in Swift :large_orange_diamond:

**Comment by lfarah** [comment]
@garnele007, do you know on what category we could add *SwiftOCR*?

**Comment by garnele007** [comment]
@lfarah I would put it under /Media/Image. I think that would be the best category.

**Comment by lfarah** [comment]
If @dkhamsing and @vsouza agree, we could add a ```/Media/Other Media``` section
