### ISSUE TITLE
WKZombie

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#789]
[WKZombie](https://github.com/mkoehnke/WKZombie) - WKZombie is a Swift framework for iOS/OSX to navigate within websites and collect data without the need of User Interface or API, also known as Headless browser. It can be used to run automated tests or manipulate websites using Javascript. :large_orange_diamond:

**Comment by vsouza** [comment]
it's like Selenium project

I believe this project is to be used (in most cases) for testing. We can add to `Other testing` category?

**Comment by lfarah** [comment]
I didn't know that... Will add to ```Other Testing```

**Comment by lfarah** [comment]
I see WKZombie as a way to scrape websites... @dkhamsing what do you think?

**Comment by dkhamsing** [comment]
Networking ?

**Comment by dkhamsing** [comment]
Could be used outside of testing

**Comment by lfarah** [comment]
@victorgama what do you think?

**Comment by victorgama** [comment]
I was following this discussion yesterday, and honestly, I don't know. I think it would fit `XML / HTML / CSV`, assuming you can (also) query the document, but given it is capable of interacting with the page itself, `Other Testing` seems more suitable.

**Comment by vsouza** [comment]
I've been thinking about, and this is nothing more than a way to query for HTML documents.
I think the category `XML / HTML / CSV` is more appropriate.

a few more projects to be added:
https://github.com/Dimillian/HackerSwifter
https://github.com/tid-kijyun/Kanna

**Comment by lfarah** [comment]
I agree with @vsouza. @dkhamsing what do you think?

**Comment by dkhamsing** [comment]
sounds good

**Comment by vsouza** [comment]
@victorgama  ?

**Comment by victorgama** [comment]
Yup. `XML / HTML / CSV` it is. 👍

**Comment by lfarah** [comment]
thanks, guys! 😉

**Comment by vsouza** [comment]
😄
