### ISSUE TITLE
Venice

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#791]
[Venice](https://github.com/VeniceX/Venice) - CSP (Coroutines, Channels, Select) for Swift :large_orange_diamond:

**Comment by vsouza** [comment]
@lfarah we can create a new category `Concurrency`. I found some others projects:

https://github.com/tidwall/Safe
https://github.com/moriturus/Concurrent
https://github.com/typelift/Concurrent

**Comment by lfarah** [comment]
[Concurrent](https://github.com/moriturus/Concurrent) doesn't have a good ```README.md```

**Comment by vsouza** [comment]
hmm. have an usage example, pod and carthage compatibility bagdes... I agree that it is not complete as it should, but I approve. what u think guys?

**Comment by dkhamsing** [comment]
don't feel too strongly about it

**Comment by lfarah** [comment]
It doesn't show how to install. That's a major thing a ```README.md``` has to do.
Compare [this awesome README](https://github.com/rakaramos/OnOffButton) with [Concurrent's](https://github.com/moriturus/Concurrent)
