### ISSUE TITLE
XcodeServerSDK

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#793]
[XcodeServerSDK](https://github.com/czechboy0/XcodeServerSDK) - Access Xcode Server API with native Swift objects. Supports Xcode Server API of Xcode 6 and 7. :large_orange_diamond:

**Comment by lfarah** [comment]
@czechboy0 do you know on what category we could add * XcodeServerSDK*?

**Comment by czechboy0** [comment]
I don't know, it's a Swift SDK for communicating with Xcode Server over its API. Continuous integration, testing, maybe service SDK? Something similar to GitHub SDK etc.

**Comment by lfarah** [comment]
@dkhamsing @naeemshaikh90 /Tools?

**Comment by victorgama** [comment]
@miguelarauj1o What happened to https://github.com/miguelarauj1o/awesome-ios/commit/1cd1ed5afe9fc5e843b78a49ef044772b8993535? It references this issue, but does not belong to `master` here. Besides, this is the only commit left open from that list.

**Comment by lfarah** [comment]
@miguelarauj1o?

**Comment by miguelarauj1o** [comment]
thinking a little bit here...
probably I made multiple changes in https://github.com/miguelarauj1o/awesome-ios/commit/1cd1ed5afe9fc5e843b78a49ef044772b8993535, but I should have done it separately, as recommended in [PULL_REQUEST_TEMPLATE](https://github.com/vsouza/awesome-ios/blob/master/.github/PULL_REQUEST_TEMPLATE.md).
So I forgot to remove this ref.

**Comment by miguelarauj1o** [comment]
Can we close this issue?

**Comment by dkhamsing** [comment]
yes
