### ISSUE TITLE
SwiftNotificationCenter

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#809]
[SwiftNotificationCenter](https://github.com/100mango/SwiftNotificationCenter) - A Protocol-Oriented NotificationCenter which is type safe, thread safe and with memory safety :large_orange_diamond:

**Comment by lfarah** [comment]
@100mango, do you know on what category we could add *SwiftNotificationCenter*?

**Comment by 100mango** [comment]
@lfarah  I think it could be added to `EventBus` or `Tools`. Thanks.

**Comment by lfarah** [comment]
Thanks @100mango. You're awesome! 😄
