### ISSUE TITLE
Library count

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#823]
> A collaborative list of **405** open-source iOS apps, your contribution is welcome :smile: (last update May 17, 2016).
> @dkhamsing how can we add this functionality to Awesome-iOS?

**Comment by dkhamsing** [comment]
Hm
Need a script to count projects .. and update README

**Comment by lfarah** [comment]
So for what I looked in *Awesome Bot* and *Open source iOS Apps*, travis calls a ruby file that filters all the urls, counts them and then another ruby file writes the README with the newest count?

**Comment by dkhamsing** [comment]
Yup, pretty easy
Gets a little more complicated if the starting point is the README

Any thoughts?

**Comment by vsouza** [comment]
but, when ruby writes in README is a new repo commit, right?

**Comment by dkhamsing** [comment]
yeah, would have to be

**Comment by lfarah** [comment]
@dkhamsing README.md is just a huge text file. I just finished doing some tests on getting all the links with *Regex* and it's pretty easy:

``` python
import re
f2 = open("README.md","r")
text = str(f2.readlines())
urls = re.findall('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', text)
print len(urls)
```

**Comment by vsouza** [comment]
so, after approve each pull request we will make a new commit 😕 ?

I think the proposal of awesome-ios site would be ideal for these features. There we can display the information with more freedom.

**Comment by dkhamsing** [comment]
sure.. except how do you know which links are projects ? I mean an approximate number is not bad.. dunno

**Comment by lfarah** [comment]
@dkhamsing I checked and It's link count - 10 (7 from the beginning of the file and 3 in the end)

**Comment by dkhamsing** [comment]
nice

**Comment by dkhamsing** [comment]
this line
> Canvas - Animate in Xcode without code http://canvaspod.io

2 links 😉

**Comment by dkhamsing** [comment]
@vsouza could always update the count just once a week or whatever since it is 
> number of projects: xxx (updated m d, 2016)

**Comment by lfarah** [comment]
@dkhamsing Oh, I didn't think about that! I always try to take these url's out of the description.
But in the end, it's easy to fix the Regex because the url needs to start with a ```[````

**Comment by dkhamsing** [comment]
Cool

**Comment by lfarah** [comment]
@dkhamsing me and @vsouza stayed for the past 4 hours and we finished the counter.
The only problem is that the ```README.md``` is doing a cache and the badge doesn't update.

Why?

**Comment by dkhamsing** [comment]
Can I see the code

**Comment by lfarah** [comment]
@dkhamsing https://github.com/lfarah/AwesomeLibCounter

**Comment by dkhamsing** [comment]
Ah I see.. not sure about the README cache but the badge should eventually update?

**Comment by lfarah** [comment]
But how does the Travis badge update and ours don't?

**Comment by lfarah** [comment]
[![Language](https://awesomelinkcounter.herokuapp.com/swift)]()
It's cached here too!

**Comment by dkhamsing** [comment]
Well mine is text.. so this probably has to do with your image host

Can you change to use shields.io and put the count there?

![](https://img.shields.io/badge/swift%20projects-888-orange.svg)

https://img.shields.io/badge/swift%20projects-888-orange.svg

**Comment by lfarah** [comment]
@dkhamsing but that's what my heroku does: it counts and then redirects to Image.shields

**Comment by dkhamsing** [comment]
😕

**Comment by lfarah** [comment]
It's been more than 12 hours and it's still cached

**Comment by lfarah** [comment]
I was [reading this](https://github.com/github/markup/issues/224#issuecomment-37663375) and they talk about the difference between ```http``` and ```https``` in the links, and then I saw this:
[![Language](http://awesomelinkcounter.herokuapp.com/swift)]() // ??
[![Language](https://awesomelinkcounter.herokuapp.com/swift)]() // Cached

**Comment by lfarah** [comment]
Nevermind... both are cached

**Comment by lfarah** [comment]
@vsouza 
> Update: The HTTPS versions also get proxied now. Assets must include Cache-Control: no-cache and ETag headers. If a badge is not updating, then it means they are not properly setting these headers. See my comment below for more info.

**Comment by lfarah** [comment]
What do we do here guys?

**Comment by miguelarauj1o** [comment]
Can we close this issue?

**Comment by dkhamsing** [comment]
Yup
