### ISSUE TITLE
Render

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#824]
[Render](https://github.com/alexdrone/Render) - Swift and UIKit a la React. :large_orange_diamond:

**Comment by lfarah** [comment]
@alexdrone do you know on what category we could add *Render*?

**Comment by alexdrone** [comment]
Probably under UI :) Thank you for your addition btw 👍

**Comment by lfarah** [comment]
Adding to *UI* right away! 

Thanks for the helping! 🎉🎉🎉
