### ISSUE TITLE
FlatBuffersSwift

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#826]
[FlatBuffersSwift](https://github.com/mzaks/FlatBuffersSwift) - This project brings FlatBuffers (an efficient cross platform serialization library) to Swift. :large_orange_diamond:

**Comment by lfarah** [comment]
@mzaks, do you know on what category we could add *FlatBuffersSwift*?

**Comment by mzaks** [comment]
I would say `Data Serialisation`

**Comment by lfarah** [comment]
@mzaks Awesome. Thanks! 😉

**Comment by mzaks** [comment]
When I close this issue:
https://github.com/mzaks/FlatBuffersSwift/issues/7
it can be also placed under JSON
Users would be able to convert JSON object into type safe FlatBuffers generated classes and serialise them as binary.

**Comment by lfarah** [comment]
Cool. Looking forward 😄
