### ISSUE TITLE
Reflection Category

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#827]
[Reflection](https://github.com/Zewo/Reflection) - Reflection provides an API for advanced reflection at runtime including dynamic construction of types. :large_orange_diamond:
[Reflect](https://github.com/CharlinFeng/Reflect) - Reflection, Dict2Model, Model2Dict, Archive :large_orange_diamond:
[EVReflection](https://github.com/evermeer/EVReflection) - Reflection based JSON encoding and decoding. Including support for NSDictionary, NSCoding, Printable, Hashable and Equatable :large_orange_diamond:
[JSONNeverDie](https://github.com/johnlui/JSONNeverDie) - Auto reflection tool from JSON to Model, user friendly JSON encoder / decoder, aims to never die :large_orange_diamond:

**Comment by vsouza** [comment]
@lfarah we have to create a new category. Reflection is a large field of computation.

Some other projects to add to category 😄 

https://github.com/kostiakoval/Mirror
https://github.com/CharlinFeng/Reflect
https://github.com/evermeer/EVReflection
https://github.com/johnlui/JSONNeverDie

**Comment by lfarah** [comment]
@vsouza Mirror doesn't work with the latest version

**Comment by lfarah** [comment]
@dkhamsing @vsouza do u guys approve it?

**Comment by dkhamsing** [comment]
👍

**Comment by lfarah** [comment]
Thanks guys!
