### ISSUE TITLE
URLPreview

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#828]
[URLPreview](https://github.com/itsmeichigo/URLPreview) - An NSURL extension for showing preview info of webpages :large_orange_diamond: [e]

**Comment by lfarah** [comment]
@itsmeichigo, do you know on what category we could add *URLPreview*? I really liked your lib 😄

**Comment by itsmeichigo** [comment]
@lfarah Thanks, I'm glad you like it. I guess the lib can be kept in that category named XML / HTML / CSV. That makes sense, right?

**Comment by lfarah** [comment]
@itsmeichigo I tried to fit *URLPreview* for weeks now and I never thought about ``` XML / HTML / CSV```, but now it definitely makes sense.

Thanks for helping! 😄
