### ISSUE TITLE
Add another Rating Star Lib

### ISSUE THREAD

**Issue by singhdd93** [vsouza/awesome-ios#830]
Please check the below Lib. I am using it and its awesome
https://github.com/hsousa/HCSStarRatingView

**Comment by singhdd93** [comment]
Any update on this ?

**Comment by victorgama** [comment]
Hi @singhdd93! Feel free to open a Pull Request. We have a [subcategory](https://github.com/vsouza/awesome-ios#rating-stars) for this kind of UI component. :)

**Comment by lfarah** [comment]
Hey @singhdd93, sorry for the delay. I just added the lib.

Thanks for contributing 😄
