### ISSUE TITLE
關於接續互動continue

### ISSUE THREAD

**Issue by KaiuCheong** [vsouza/awesome-ios#831]
如果我想要將一小段文字由手機傳到電腦的command c中有什方向去查，目前只找到接續互動相關東西但介紹不是很明白

**Comment by lfarah** [comment]
Hey @KaiuCheong, we only accept issues and pull requests in English, so the whole world can understand and help you!

**Comment by KaiuCheong** [comment]
what a poor English with me,  I do my best! 
If I want to send a short color code to the MAC temporary memory area ( command + c ) from iphone application. 
I searching about "Continuity" But I can't find out any article  to discussion this method on coding with objective-c

**Comment by lfarah** [comment]
Hey @KaiuCheong, your english is totally fine 😉 

I don't think there are any libraries for that. I'm closing this issue but If I find anything I'll let you know
