### ISSUE TITLE
Pancake

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#833]
[Pancake](https://github.com/JPMartha/Pancake) - A command line program to be run on OS X's Terminal utility that performs generating a Swift documentation as Markdown format :large_orange_diamond:

**Comment by lfarah** [comment]
@JPMartha, do you know where we could add your library?

**Comment by JPMartha** [comment]
Hi @lfarah, nice to meet you! Thanks for your mention :)

Is this work urgent?
Because I am busy until this Saturday, but after it is over, I might be able to contribute your work.

**Comment by lfarah** [comment]
Hey @JPMartha, have your time. I know that the life of us developers can be really busy sometimes!

**Comment by JPMartha** [comment]
Hi @lfarah, I'm really sorry for the late reply.

I think `Tools` is suitable for my library.
By the way, it's unfinished, is it Okay?

**Comment by lfarah** [comment]
@JPMartha do you know when it will be finished? I'll keep this issue open until you finish.
Let me know how I can help 😉

**Comment by lfarah** [comment]
Closing this as it's not in Swift 3
