### ISSUE TITLE
swiftTheme

### ISSUE THREAD

**Issue by iceman201** [vsouza/awesome-ios#836]
[SwiftTheme](https://github.com/jiecao-fm/SwiftTheme) - Powerful theme/skin manager for iOS 7+ :large_orange_diamond:

**Comment by lfarah** [comment]
[SwiftTheme](https://github.com/jiecao-fm/SwiftTheme) - Powerful theme/skin manager for iOS 7+ :large_orange_diamond:

**Comment by lfarah** [comment]
@jiecao-fm do you know on what category we could add *SwiftTheme*?

**Comment by lfarah** [comment]
@iceman201 thanks for contributing! 😄 
I'll do my best to find a place for the lib as fast as possible 🚀 🚀 🚀
