### ISSUE TITLE
Flow

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#868]
[Flow](https://github.com/JohnSundell/Flow) - Operation Oriented Programming in Swift :large_orange_diamond:

**Comment by lfarah** [comment]
@JohnSundell, do you know on what category we could add *Flow*?

**Comment by JohnSundell** [comment]
@lfarah how about "Concurrency"?

**Comment by lfarah** [comment]
@JohnSundell that should work. Thanks! 😄

**Comment by onmyway133** [comment]
I very much like this `Flow`
