### ISSUE TITLE
InstagramAuthViewController

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#869]
[InstagramAuthViewController](https://github.com/Isuru-Nanayakkara/InstagramAuthViewController) - A ViewController for Instagram authentication. :large_orange_diamond:

**Comment by lfarah** [comment]
@Isuru-Nanayakkara, do you know on what category we could add *InstagramAuthViewController*?

**Comment by Isuru-Nanayakkara** [comment]
Hi, I think the best one would be Authentication.

**Comment by lfarah** [comment]
You're fast! 🚀 🚀 🚀 

Thanks for helping 😄

**Comment by Isuru-Nanayakkara** [comment]
haha thanks for adding it to the list and your continued interest 🙂🏽  Appreciate it 👍
