### ISSUE TITLE
EasyAbout

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#873]
[EasyAbout](https://github.com/JARMourato/EasyAbout) - A way to easily add Cocoapod licenses and App Version to your iOS App using the Settings Bundle

**Comment by lfarah** [comment]
@JARMourato what category can we put *EasyAbout*?

**Comment by JARMourato** [comment]
Hi @lfarah, under the categories you have here, I'd put it in _Utility_ or _Tools_. 

Thanks for considering _EasyAbout_ :)

**Comment by lfarah** [comment]
*Utility* it is 🚀🚀 

Thanks for helping us out 😄
