### ISSUE TITLE
Chrome style pull to refresh

### ISSUE THREAD

**Issue by Antondomashnev** [vsouza/awesome-ios#882]
Hi there,

[ADChromePullToRefresh](https://github.com/Antondomashnev/ADChromePullToRefresh) Chrome iOS app style pull to refresh control in `swift`

**Comment by lfarah** [comment]
Hey @Antondomashnev, great library!
You can add it in [```UI/Pull To Refresh```](https://github.com/vsouza/awesome-ios#pull-to-refresh).

You can make a pull request in the ```README.md``` to add your library or I could do that for you.
