### ISSUE TITLE
Add IQAudioRecorderController

### ISSUE THREAD

**Issue by singhdd93** [vsouza/awesome-ios#886]
[IQAudioRecorderController](https://github.com/hackiftekhar/IQAudioRecorderController) - A drop-in universal library allows to record audio within the app with a nice User Interface.

Nice and Regularly updated project.
Easy to integrate.

**Comment by lfarah** [comment]
Hey @singhdd93, sorry for the delay 😢
I'm gonna help *IQAudioRecorderController* to organized their ```Readme.md``` and then we can send it to AwesomeiOS.

Thanks for the contribution 😄

**Comment by lfarah** [comment]
@singhdd93 just made a pull request over there: https://github.com/hackiftekhar/IQAudioRecorderController/pull/30

**Comment by lfarah** [comment]
Done. Adding it to Awesome! 😄
