### ISSUE TITLE
SKSplashView

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#894]
[SKSplashView](https://github.com/sachinkesiraju/SKSplashView) - Create custom animated splash views similar to the ones in the Twitter, Uber and Ping iOS app.

**Comment by lfarah** [comment]
@sachinkesiraju what section do you think we can add Splashview?

**Comment by sachinkesiraju** [comment]
@lfarah I think it could be put in the UI category. Thanks for the add!
