### ISSUE TITLE
AssistantKit

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#895]
[AssistantKit](https://github.com/anatoliyv/AssistantKit) - Easy way to detect iOS device properties, OS versions and work with screen sizes. Powered by Swift. :large_orange_diamond:

**Comment by lfarah** [comment]
@anatoliyv on what section do you think we can add ```AssistantKit```?

**Comment by anatoliyv** [comment]
@lfarah I think `Utility` is the best place. Thank you.

**Comment by lfarah** [comment]
@anatoliyv Thanks for contributing and good job on the library 😉
