### ISSUE TITLE
Collection View section

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#898]
* [PagingView](https://github.com/KyoheiG3/PagingView) - Infinite paging, Smart auto layout, Interface of similar to UIKit. :large_orange_diamond:
 * [DisplaySwitcher](https://github.com/Yalantis/DisplaySwitcher) - Custom transition between two collection view layouts :large_orange_diamond:
 * [CHTCollectionViewWaterfallLayout](https://github.com/chiahsien/CHTCollectionViewWaterfallLayout) - The waterfall (i.e., Pinterest-like) layout for UICollectionView.
 * [FMMosaicLayout](https://github.com/fmitech/FMMosaicLayout) - A drop-in mosaic collection view layout with a focus on simple customizations.

**Comment by lfarah** [comment]
#781

**Comment by lfarah** [comment]
@victorgama  @dkhamsing @vsouza do u guys know any other Collection View libs?

**Comment by victorgama** [comment]
@lfarah I've used [FMMosaicLayout](https://github.com/fmitech/FMMosaicLayout) once or twice, but I'm afraid it is not longer being actively developed. Anyway, it still fits in the `Has a commit from less than 2 years ago` rule. :)

**Comment by dkhamsing** [comment]
I've used https://github.com/chiahsien/CHTCollectionViewWaterfallLayout but it's just a layout

**Comment by lfarah** [comment]
We have a problem. Just realized that there are a lot of libs that work both for ```CollectionViews``` and ```TableViews```. Should we do a ```TableView/CollectionView``` section?

**Comment by lfarah** [comment]
Talked to @vsouza and we're doing a ```TableView / CollectionView``` section
