### ISSUE TITLE
Update CC Link

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#904]
Details here cc4f7b7ff20c1d8d27687657ea82edf8d9e7f113 
What's the current Creative Commons link we should use?

**Comment by dkhamsing** [comment]
@victorgama hope you can help 😄

**Comment by victorgama** [comment]
Their tool suggests `http://creativecommons.org/licenses/by/4.0`, but it is 503'ing right now. Will retry later. ✨

**Comment by victorgama** [comment]
Okay, looks like we have a small issue here. The Readme says the license is "Public domain", but...

> Creative Commons has retired this legal tool and does not recommend that it be applied to works.


They're recommending [Attribution 4.0 International](http://creativecommons.org/licenses/by/4.0/) instead. Shall we update it?

cc @vsouza @dkhamsing @lfarah

**Comment by vsouza** [comment]
I was talking with @lfarah and we think is more appropriated change Awesome-iOS license to MIT License, what u think guys?

**Comment by victorgama** [comment]
Given Awesome-iOS is just a "curated index", why not [WTFPL](http://www.wtfpl.net)?

**Comment by lfarah** [comment]
There were some websites using our content and having ads without mentioning us. I think we're better protected under MIT

**Comment by victorgama** [comment]
Oh. Okay, considering @lfarah's last comment, it makes sense. 😛

**Comment by vsouza** [comment]
@dkhamsing ?

**Comment by dkhamsing** [comment]
not too sure, i will trust you guys

**Comment by vsouza** [comment]
#907
