### ISSUE TITLE
Ejecta

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#905]
[Ejecta](https://github.com/phoboslab/Ejecta) - A Fast, Open Source JavaScript, Canvas & Audio Implementation for iOS

> Ejecta is like a Browser without the Browser. It's specially crafted for Games and Animations. It has no DIVs, no Tables, no Forms – only Canvas and Audio elements. This focus makes it fast.
> 
> JavaScript code is executed directly by a JavaScript VM (JavaScriptCore), the HTML5 Canvas 2D and WebGL API is implemented in native code with OpenGL, Audio is implemented with OpenAL. Several other APIs (touch, accelerometer, localStorage, gamepad) behave like those in a real browser.
> 
> Many HTML5 Games run out of the box, or with minimal modifications – with better performance, better sound support, Game Center integration and more.

**Comment by lfarah** [comment]
Is it similar to [WKZombie](https://github.com/mkoehnke/WKZombie)??

**Comment by lfarah** [comment]
Closing this due inactivity
