### ISSUE TITLE
Sorting before submitting a PR

### ISSUE THREAD

**Issue by bre7** [vsouza/awesome-ios#919]
Add a script to sort the list by popularity ? Library and Frameworks => Stars ? Or maybe some type of avg using stars+CocoaPods downloads ?

**Comment by lfarah** [comment]
hey @bre7, me and @vsouza are working in a 100% Swift website that would do that.
Would you be interested in helping us?

**Comment by bre7** [comment]
Hey. Sure, sounds fun. Not a lot of free time atm but I'm happy to help out if I can.

**Comment by bre7** [comment]
Bump: Check out js.coach (similar but for JS libs).

GH project here: https://github.com/dmfrancisco/JS.coach

**Comment by lfarah** [comment]
@vsouza /\

**Comment by lfarah** [comment]
We decided that we won't do that on Github. Our website will do that once it is launched

**Comment by bre7** [comment]
👍

**Comment by bre7** [comment]
Which web framework are you guys using (or going to use) ? Vapor ? Perfect ? Kitura ? Zewo ?

**Comment by vsouza** [comment]
@bre7 at this moment I've been working on a service to get data in a private database, to serve all users. About frameworks, it will be a later decision. 

Do you have some advice for us? All contribution will be appreciated. 

Thank you ❤️

**Comment by bre7** [comment]
Not really, I've been trying Vapor but not for production apps, next on my list are Perfect and Kitura. I really liked Vapor's modular approach (Leaf for templates, Fluent, etc.) and cli-toolbox.

You might want to check our benchmarks and comparison guides (Vapor 2.0 is going to be released soon).

**Comment by vsouza** [comment]
@bre7 I'm very excited about this benchmark: 

https://medium.com/@rymcol/benchmarks-for-the-top-server-side-swift-frameworks-vs-node-js-24460cfe0beb#.p1t8i8j1j
