### ISSUE TITLE
Word  / Tag Cloud UI

### ISSUE THREAD

**Issue by luto65** [vsouza/awesome-ios#940]
I am looking for a TagCloud / WordCloud UI for iOS that I could embed in my app.
I've already implemented a TagCloud by myself - however it is not very elegant / can'T really compare with Wordle  .... Is anybody there that would like to contribute that ?

**Comment by lfarah** [comment]
[DBSphereTagCloud](https://github.com/dongxinb/DBSphereTagCloud) is the best lib I found.
For a better UI and UX, I'd recommend using 2D tags, and those you can find at our [/Tag Section](https://github.com/vsouza/awesome-ios#tag)

Hope I was able to help! 😄

**Comment by lfarah** [comment]
I'm gonna close this. Let me know if there's anything else I can help you with!
