### ISSUE TITLE
Parsing Category

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#944]
I talked to @vsouza and we had the idea of creating a Parser category which was ```JSON```, ```CSV```, ```XML+HTML``` and an ```Other``` category with projects like [WKZombie](https://github.com/mkoehnke/WKZombie) and [URLPreview](https://github.com/itsmeichigo/URLPreview).
We decided that **XML** and **HTML** should be in the same section because there are a lot of libraries that support both, so I'd be difficult to separate them.

#### Parser
* CSV
* JSON
* XML+HTML
* Other

What do you guys think? 😃

**Comment by lfarah** [comment]
@dkhamsing @victorgama what are your thoughts? 🤔

**Comment by dkhamsing** [comment]
Sounds good

**Comment by dkhamsing** [comment]
Maybe should be called Parsing
