### ISSUE TITLE
Encryption Category

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#947]
Just discovered [we have an Encryption Category](https://github.com/vsouza/awesome-ios#encryption), but it was never on our **Contents**.
Should we keep it or kill it since we already have [Security Category](https://github.com/vsouza/awesome-ios#security)? 🤔

**Comment by dkhamsing** [comment]
Could be a sub category

**Comment by lfarah** [comment]
Alright, that works!
