### ISSUE TITLE
Readme Organization

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#954]
Hey guys, now that we have our Mongo database, I believe we can do so much with the organization of the libs.
I suggest the next steps are the following:
1. ~~Fix spacing before the \* in some sections #960~~
2.  ~~Update descriptions #949~~ 
3. Update library names
4. Check all the libs that weren't updated within the last 2 years
5. Check all the Swift libs that weren't updated within the last 6 months

What do you guys think?

**Comment by vsouza** [comment]
let's do this!!!

**Comment by dkhamsing** [comment]
uh cool? 
can u explain what you have in mongo, how do we look at it or edit it?

**Comment by vsouza** [comment]
@dkhamsing 

I wrote a scrapper (with golang), which runs every two hours collecting data from all awesome-iOS projects.
The initial intention is not to leave the open base but have a consultation interface (API).

But if you are interested we can give you access without problems.

**Comment by dkhamsing** [comment]
hmm ok
does @lfarah mean to update the readme, have it generated?

**Comment by lfarah** [comment]
Yes, now we need to Re-generate our Readme from the Mongo, but since there are a lot of libraries and it's never perfect, I want to do it in small steps, as mentioned in this issue's description

**Comment by dkhamsing** [comment]
can u do it in a branch so we can verify the changes?

**Comment by lfarah** [comment]
Sure

**Comment by EvgenyKarkan** [comment]
Hi guys, thanks for your efforts, first of all. 
Please find some spare time to consider replacing `EKAlgorithms` repo reference from `Utilities` to `Data Structures / Algorithms` category. 
I guess it will be a more predictable place.
Have a nice day!

**Comment by dkhamsing** [comment]
@EvgenyKarkan thanks, will open an issue

**Comment by miguelarauj1o** [comment]
@lfarah, the second one was made in #1490.

**Comment by miguelarauj1o** [comment]
And about 3, 4 and 5?

**Comment by vsouza** [comment]
@miguelarauj1o I have a script for this. ASAP I'll post here the list :smile:

**Comment by miguelarauj1o** [comment]
Great!

**Comment by vsouza** [comment]
Guys, I made a query on awesome-ios database© and returned zero results for projects weren't updated within the last 2 years. (I can be wrong, but I think  it's the true)

In projects that weren't updated in last 6 months, we have twelve results, eleven writter in Objective-C and this one in Swift:
[https://github.com/singcodes/BundleInfos](https://github.com/singcodes/BundleInfos)

But we have eleven results in Objective-C, just for information 😄

**Comment by dkhamsing** [comment]
Closing this
Feel free to open a new issue if needed

Thx
