### ISSUE TITLE
Unable to access Obj C and Swift projects

### ISSUE THREAD

**Issue by JMatharu** [vsouza/awesome-ios#955]
![untitled](https://cloud.githubusercontent.com/assets/5781893/16937722/8b77a9b6-4d3f-11e6-9693-dff062580a5f.png)

Clicking on projects, moves to 404 github page.

**Comment by dkhamsing** [comment]
@JMatharu all the content is in the readme.. not sure if the links should go anywhere.. yet
thx for the report

cc @lfarah

**Comment by lfarah** [comment]
Hey @JMatharu, I did that on purpose. These are just badges showing the count of libraries for each language. Unfortunately they are on a free Heroku account and there are only so many requests that can be done, so I'm trying to avoid more requests by people who clicked on the badges.
Me and @vsouza are about to move this badge to our [awesomeiOS.com](awesomeios.com), so we'll be able to have more requests
