### ISSUE TITLE
WAMapping

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#967]
[WAMapping](https://github.com/Wasappli/WAMapping) - A library to turn dictionary into object and vice versa for iOS. Designed for speed!

**Comment by lfarah** [comment]
@Wasappli do you know where we could add it?

**Comment by lfarah** [comment]
@dkhamsing @naeemshaikh90 /JSON?

**Comment by victorgama** [comment]
@lfarah `JSON` it is!
