### ISSUE TITLE
WANetworkRouting

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#968]
[WANetworkRouting](https://github.com/Wasappli/WANetworkRouting) - An iOS library to route API paths to objects on client side with request, mapping, routing and auth layers

**Comment by lfarah** [comment]
@Wasappli same for this one 😄

**Comment by lfarah** [comment]
@dkhamsing @naeemshaikh90 /Networking?

**Comment by victorgama** [comment]
@lfarah `Networking` fits this one.
