### ISSUE TITLE
Implement Danger

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#972]
Dear @dkhamsing, our CI God,
Do you think it would be cool to add [Danger](http://danger.systems/reference.html) to AwesomeiOS?
If so, can you do it? I don't wanna mess up with the bots you're already running

**Comment by dkhamsing** [comment]
Haha
We can try it, if anything the current setup can be lauded or turned off

What rules do you want to enforce?

**Comment by dkhamsing** [comment]
Oops fixed a typo

**Comment by lfarah** [comment]
ENSURE THERE IS A SUMMARY FOR A PR
fail "Please provide a summary in the Pull Request description" if github.pr_body.length < 5

WARN WHEN THERE ARE MERGE COMMITS IN THE DIFF
if commits.any? { |c| c.message =~ /^Merge branch 'master'/ }
   warn 'Please rebase to get rid of the merge commits in this PR'
end

ONLY ONE LIB PER PR (I created 😉 )
fail "Please only add one library per PR" if git.lines_of_code > 1

What do you think? 🤔
