### ISSUE TITLE
PJFDataSource

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#974]
https://github.com/square/PJFDataSource

> PJFDataSource is a small library that provides a simple, clean architecture for your app to manage its data sources while providing a consistent user interface for common content states (i.e. loading, loaded, empty, and error).

**Comment by dkhamsing** [comment]
oops

**Comment by victorgama** [comment]
@dkhamsing I think `UI`/`Table View / Collection View` fits this one, as we have other data sources there.
