### ISSUE TITLE
PickerView Category

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#976]
- [ActionSheetPicker-3.0](https://github.com/skywinder/ActionSheetPicker-3.0/) - Quickly reproduce the dropdown UIPickerView / ActionSheet functionality on iOS.
- [PickerView](https://github.com/filipealva/PickerView) - A customizable alternative to UIPickerView in Swift. :large_orange_diamond:
- [DatePickerDialog](https://github.com/squimer/DatePickerDialog-iOS-Swift) - A Swift library that displays an UIDatePicker within an UIAlertView :large_orange_diamond:
- [CZPicker](https://github.com/chenzeyu/CZPicker) - A picker view shown as a popup for iOS.
- [IQDropDownTextField](https://github.com/hackiftekhar/IQDropDownTextField) - TextField with DropDown support using UIPickerView
- [SRKControls](https://github.com/sag333ar/SRKControls) - A Custom control which turns UITextfield to item-picker & date-picker. :large_orange_diamond:
- [AIDatePickerController](https://github.com/alikaragoz/AIDatePickerController) - :date: UIDatePicker modally presented with iOS 7 custom transitions.

**Comment by lfarah** [comment]
@vsouza @dkhamsing @miguelarauj1o?

**Comment by dkhamsing** [comment]
Maybe name it Picker or Selection

**Comment by lfarah** [comment]
I was following what we have for */Table View*, */TextField*, */Collection View*
