### ISSUE TITLE
Report link issues in pull request

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#983]
[danger-junit](https://github.com/orta/danger-junit) lets you report your test suite problems back to the PR elegantly, so instead of having to open Travis every time to see why the test failed, it's already there on the PR.

**Comment by lfarah** [comment]
Oh holy CI God, can you help us again? @dkhamsing

**Comment by dkhamsing** [comment]
Unfortunately we do not generate the supported xml test output so this is not yet possible

**Comment by lfarah** [comment]
I was reading and apparently Travis doesn't support JUnit XML 😢

**Comment by lfarah** [comment]
Orta on Twitter:
> it’s not really the job of travis to do it per-project, for example xcpretty outputs in JUnit ( we use it in artsy/Eigen )

**Comment by dkhamsing** [comment]
Might be able to achieve something similar by parsing results, will keep you posted
