### ISSUE TITLE
Additions?

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#984]
@lfarah  hey buddy, I bookmarked these a while back to add here.. hope it's ok that I create this issue

- [x] https://github.com/algolia/algoliasearch-client-swift
- [x] https://github.com/makemoji/MakemojiSDK
- [x] https://github.com/DeveloperLx/LxDBAnything
- [x] https://github.com/Instapaper/LinkPreviewCustomAction
- [x] https://github.com/linkedin/Selene
- [x] https://github.com/bignerdranch/CoreDataStack
- [x] https://github.com/czechboy0/Buildasaur
- [x] https://github.com/conradev/nes-ios
- [x] https://github.com/TimOliver/TOActionSheet
- [x] https://github.com/NewAmsterdamLabs/ZOZolaZoomTransition
- [x] https://github.com/Raizlabs/RZTransitions
- [x] https://github.com/xareelee/XLTestLog
- [x] https://github.com/overboming/ZCAnimatedLabel
- [x] https://github.com/IFTTT/FastttCamera
- [x] https://github.com/IFTTT/IFTTTLaunchImage
- [x] https://github.com/Yalantis/FoldingTabBar.iOS
- [x] https://github.com/Raizlabs/BonMot
- [x] https://github.com/northernspark/AHDirectionsObject
- [x] https://github.com/macoscope/NotificationController
- [x] https://github.com/uber/signals-ios
- [x] https://github.com/nevyn/MeshPipe
- [x] https://github.com/swisspol/XLFacility
- [x] https://github.com/eklipse2k8/FilterKit
- [x] https://github.com/hectr/MRWorldMapView
- [x] https://github.com/Automatic/Automatic-iOS-SDK
- [x] https://github.com/samdmarshall/debugDescription
- [x] https://github.com/IFTTT/jot 
- [x] https://github.com/johnno1962/Xtrace
- [x] https://github.com/toco/TOCAssetCatalogBackground
- [x] https://github.com/0xced/ABGetMe
- [x] https://github.com/andreamazz/AMWaveTransition
- [x] https://github.com/andreamazz/UITextField-Shake
- [x] https://github.com/FlexMonkey/ShinpuruImage/blob/master/README.md
- [x] https://github.com/omichde/BOMFeedback
- [x] https://github.com/robotmedia/RMStore
- [x] https://github.com/honkmaster/TTOpenInAppActivity
- [x] https://github.com/wtmoose/TLLayoutTransitioning
- [x] https://github.com/facebook/KVOController/
- [x] https://github.com/calebd/CMDQueryStringSerialization
- [x] https://github.com/LoganWright/Genome
- [x] https://github.com/LoganWright/Polymer
- [x] https://github.com/Inferis/IIAutoNSCoding
- [x] https://github.com/square/Aardvark
- [x] https://github.com/mergesort/UIViewController-Sharing
- [x] https://github.com/sarahscott/AREasyBadge
- [x] https://github.com/oarrabi/Download-Manager
- [x] https://github.com/oarrabi/OAStackView
- [x] https://github.com/AriX/MagicKit
- [x] https://github.com/qzs21/SSWaveView
- [x] https://github.com/edwinbosire/DropMenu
- [x] https://github.com/Cocoanetics/DTLoupe
- [x] https://github.com/kevinhartman/LiquidKit
- [x] https://github.com/gekitz/GKSlidingText
- [x] https://github.com/sxyx2008/awesome-ios-animation
- [x] https://github.com/patr1ck/Provocateur
- [x] https://github.com/sferrini/SFJumpToLine
- [x] https://github.com/gemr/sheriff
- [x] https://github.com/DavdRoman/Bohr
- [x] https://github.com/Draveness/DKNightVersion
- [x] https://github.com/Skyscanner/Dixie
- [x] https://github.com/freerunnering/HomeKitBridge
- [x] https://github.com/DanielTomlinson/DANPromise
- [x] https://github.com/antiguab/BAFluidView
- [x] https://github.com/MichaelBuckley/MAIKit
- [x] https://github.com/Legoless/Alpha
- [x] https://github.com/akane/EventListener
- [x] https://github.com/Produkt/PDKTModelBuilder
- [x] https://github.com/card-io/card.io-iOS-SDK
- [x] https://github.com/jumartin/Calendar
- [x] https://github.com/pinterest/PINCache
- [x] https://github.com/pinterest/ios-pdk
- [x] https://github.com/bumaociyuan/zxIpaServer

**Comment by lfarah** [comment]
Not a problem at all... there are way too many to create issues.
Do you want me to add them?

**Comment by lfarah** [comment]
I also have my list of libs....
<img width="949" alt="screen shot 2016-08-01 at 11 55 08 am" src="https://cloud.githubusercontent.com/assets/6511079/17298055/cec31c38-57de-11e6-942f-cfc09baef9b2.png">

**Comment by dkhamsing** [comment]
yeah you or anyone else can add em, if they are good :)

**Comment by lfarah** [comment]
@dkhamsing I checked all of them because I curated and added to my list of libs. Should we close this?

**Comment by dkhamsing** [comment]
Yes thx
