### ISSUE TITLE
Buildasaur

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#988]
[Buildasaur](https://github.com/czechboy0/Buildasaur) - Automatic testing of your Pull Requests on GitHub and BitBucket using Xcode Server. Keep your team productive and safe. Get up and running in minutes. @buildasaur :large_orange_diamond:

**Comment by lfarah** [comment]
@czechboy0 on what category o you think we can add?

**Comment by czechboy0** [comment]
Tools or Testing?
