### ISSUE TITLE
algoliasearch-client-swift

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#989]
[algoliasearch-client-swift](https://github.com/algolia/algoliasearch-client-swift) - Algolia Search API Client for Swift :large_orange_diamond:

**Comment by lfarah** [comment]
@algolia on what category do you think we can add it?

**Comment by victorgama** [comment]
@lfarah `SDK`/`Official`?

**Comment by lfarah** [comment]
👍
