### ISSUE TITLE
GCDWebServer

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#991]
[GCDWebServer](https://github.com/swisspol/GCDWebServer) - Lightweight GCD based HTTP server for OS X & iOS (includes web based uploader & WebDAV server)

**Comment by lfarah** [comment]
@swisspol on what category do you think we can add it?

**Comment by swisspol** [comment]
Sorry, I'm not familiar with your project, I'll let you guys pick what's best 😄

**Comment by victorgama** [comment]
We can put this one on `Server`
