### ISSUE TITLE
Change Switch category name

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#995]
There are a lot of _Segmented Control_ libs inside _/Switch_ since they are really similar. Maybe we could change the name of the category to _/Switch & Segmented Control_

**Comment by lfarah** [comment]
@dkhamsing what do you think?

**Comment by serhii-londar** [comment]
@lfarah How about to create two separate section for Switch and Segmented Control instead of renaming one section?

**Comment by dkhamsing** [comment]
Sounds good 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
