### ISSUE TITLE
KVO category

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#997]
[KVOController](https://github.com/facebook/KVOController) - Simple, modern, thread-safe key-value observing for iOS and OS X.

**Comment by dkhamsing** [comment]
@arasu01 @serhii-londar can we put this in an existing category ?

**Comment by serhii-londar** [comment]
Hi @dkhamsing I sugest to put it into **Reactive Programming** section. What do you think?

**Comment by arasu01** [comment]
@dkhamsing : We should create a new category for it.

**Comment by dkhamsing** [comment]
@arasu01 would we move anything else to the new category? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by arasu01** [comment]
No, as of now.

**Comment by dkhamsing** [comment]
I am ok with a KVO category

Can we move this one there as well?

> Hanson - Lightweight observations and bindings in Swift, with support for KVO and NotificationCenter.

@arasu01 @serhii-londar @Mylittleswift
