### ISSUE TITLE
Warnings-xcconfig

### ISSUE THREAD

**Issue by lfarah** [vsouza/awesome-ios#999]
[Warnings-xcconfig](https://github.com/boredzo/Warnings-xcconfig) - An xcconfig (Xcode configuration) file for easily turning on a boatload of warnings in your project or its targets.

**Comment by lfarah** [comment]
@boredzo on what category do you think we can add it?

**Comment by boredzo** [comment]
@lfarah Code Quality.

**Comment by lfarah** [comment]
@boredzo thanks for helping us out!
